@startuml
left to right direction
package "taskt.Core"{
class "SafeLocalListenerSettings" {
+StartListenerOnStartup : Boolean <<get>> 
+LocalListeningEnabled : Boolean <<get>> 
+RequireListenerAuthenticationKey : Boolean <<get>> 
+ListeningPort : Int32 <<get>> 
+AuthKey : String <<get>> 
+EnableWhitelist : Boolean <<get>> 
+IPWhiteList : String <<get>> 
#localListenerSettings : taskt.Core.LocalListenerSettings
}
}

package "taskt.Core"{
Interface "ILocalListenerSettings" {
+{abstract} StartListenerOnStartup : Boolean <<get>> <<abstract>> 
+{abstract} LocalListeningEnabled : Boolean <<get>> <<abstract>> 
+{abstract} RequireListenerAuthenticationKey : Boolean <<get>> <<abstract>> 
+{abstract} ListeningPort : Int32 <<get>> <<abstract>> 
+{abstract} AuthKey : String <<get>> <<abstract>> 
+{abstract} EnableWhitelist : Boolean <<get>> <<abstract>> 
+{abstract} IPWhiteList : String <<get>> <<abstract>> 
}
}

taskt.Core.SafeLocalListenerSettings ..|> taskt.Core.ILocalListenerSettings
@enduml