@startuml
BeginLoopForDataTableCommand --> ADataTableInputDataTableCommands
BeginLoopForDataTableCommand --> IHaveLoopAdditionalCommands
ADataTableInputDataTableCommands --> ScriptCommand
ADataTableInputDataTableCommands --> IDataTableProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml