@startuml
BeginMultiLoopCommand --> ScriptCommand
BeginMultiLoopCommand --> IHaveDataTableElements
BeginMultiLoopCommand --> IHaveLoopAdditionalCommands
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml