@startuml
BeginNumberOfTimesLoopCommand --> ScriptCommand
BeginNumberOfTimesLoopCommand --> IHaveLoopAdditionalCommands
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml