@startuml
BeginLoopForDictionaryCommand --> ADictionaryInputDictionaryCommands
BeginLoopForDictionaryCommand --> IHaveLoopAdditionalCommands
ADictionaryInputDictionaryCommands --> ScriptCommand
ADictionaryInputDictionaryCommands --> IDictionaryProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml