@startuml
BeginLoopForListCommand --> AListInputListCommands
BeginLoopForListCommand --> IHaveLoopAdditionalCommands
AListInputListCommands --> ScriptCommand
AListInputListCommands --> IListProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml