@startuml
AddListItemCommand --> AListBothListCommands
AListBothListCommands --> AListInputListCommands
AListInputListCommands --> ScriptCommand
AListInputListCommands --> IListProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml