@startuml
ConvertListToVisualizedTextCommand --> AListGetFromListCommands
AListGetFromListCommands --> AListInputListCommands
AListGetFromListCommands --> IListGetFromListProperties
AListInputListCommands --> ScriptCommand
AListInputListCommands --> IListProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml