@startuml
RemoveListItemCommand --> AListIndexCommands
AListIndexCommands --> AListInputListCommands
AListIndexCommands --> IListIndexProperties
AListInputListCommands --> ScriptCommand
AListInputListCommands --> IListProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml