@startuml
SliceListCommand --> AListCreateFromListCommands
AListCreateFromListCommands --> ScriptCommand
AListCreateFromListCommands --> IListCreateFromListProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml