@startuml
SortListCommand --> AListCreateFromListCommands
AListCreateFromListCommands --> ScriptCommand
AListCreateFromListCommands --> IListCreateFromListProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml