@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
class "ReplaceDataTableValueCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbReplaceAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_ValueType : String <<get>> <<set>> 
+v_ReplaceAction : String <<get>> <<set>> 
+v_ReplaceActionParameterTable : DataTable <<get>> <<set>> 
+v_NewValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "ADataTableBothDataTableCommands"{
+v_DataTable : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "AddDataTableColumnCommand" <<sealed>> {
+RunCommand() : void 
+v_AddColumnName : String <<get>> <<set>> 
+v_IfColumnExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "AddDataTableRowCommand" <<sealed>> {
+RunCommand() : void 
+BeforeValidate() : void 
+v_AddDataDataTable : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "AddDataTableRowsByDataTableCommand" <<sealed>> {
+RunCommand() : void 
+v_DataTable : String <<get>> <<set>> 
+v_RowName : String <<get>> <<set>> 
+v_WhenColumnNotExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "AddDataTableRowByDictionaryCommand" <<sealed>> {
+RunCommand() : void 
+v_DataTable : String <<get>> <<set>> 
+v_RowName : String <<get>> <<set>> 
+v_WhenColumnNotExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SearchAndDeleteDataTableRowsCommand" <<sealed>> {
+RunCommand() : void 
+Render() : List
+GetDisplayValue() : String
+v_SearchItem : String <<get>> <<set>> 
+v_AndOr : String <<get>> <<set>> 
}
}

taskt.Core.Automation.Commands.ReplaceDataTableValueCommand --|> taskt.Core.Automation.Commands.ADataTableBothDataTableCommands
taskt.Core.Automation.Commands.AddDataTableColumnCommand --|> taskt.Core.Automation.Commands.ADataTableBothDataTableCommands
taskt.Core.Automation.Commands.AddDataTableRowCommand --|> taskt.Core.Automation.Commands.ADataTableBothDataTableCommands
taskt.Core.Automation.Commands.AddDataTableRowsByDataTableCommand --|> taskt.Core.Automation.Commands.ADataTableBothDataTableCommands
taskt.Core.Automation.Commands.AddDataTableRowByDictionaryCommand --|> taskt.Core.Automation.Commands.ADataTableBothDataTableCommands
taskt.Core.Automation.Commands.SearchAndDeleteDataTableRowsCommand --|> taskt.Core.Automation.Commands.ADataTableBothDataTableCommands
@enduml