@startuml
ConvertDataTableColumnToDictionaryCommand --> ADataTableGetFromDataTableColumnCommands
ConvertDataTableColumnToDictionaryCommand --> IDictionaryResultProperties
ADataTableGetFromDataTableColumnCommands --> ADataTableColumnCommands
ADataTableGetFromDataTableColumnCommands --> IResultProperties
ADataTableColumnCommands --> ADataTableInputDataTableCommands
ADataTableColumnCommands --> IDataTableColumnProperties
ADataTableInputDataTableCommands --> ScriptCommand
ADataTableInputDataTableCommands --> IDataTableProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml