@startuml
CopyDataTableCommand --> ADataTableCreateFromDataTableCommands
ADataTableCreateFromDataTableCommands --> ScriptCommand
ADataTableCreateFromDataTableCommands --> IDataTableCreateFromDataTableProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml