@startuml
ExportDataTableAsTextFileCommand --> ADataTableInputDataTableCommands
ADataTableInputDataTableCommands --> ScriptCommand
ADataTableInputDataTableCommands --> IDataTableProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml