@startuml
FilterDataTableRowByColumnValueCommand --> ADataTableCreateFromDataTableCommands
FilterDataTableRowByColumnValueCommand --> IDataTableColumnPositionProperties
FilterDataTableRowByColumnValueCommand --> IFilterValueProperties
FilterDataTableRowByColumnValueCommand --> IHaveDataTableElements
ADataTableCreateFromDataTableCommands --> ScriptCommand
ADataTableCreateFromDataTableCommands --> IDataTableCreateFromDataTableProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml