@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
Interface "IDataTableGetFromDataTable" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "IResultProperties" {
+{abstract} v_Result : String <<get>> <<set>> <<abstract>> 
}
}

taskt.Core.Automation.Commands.IDataTableGetFromDataTable --|> taskt.Core.Automation.Commands.IResultProperties
@enduml