@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
Interface "IDataTableRowProperties" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "IDataTableProperties" {
+{abstract} v_DataTable : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IDataTableRowPositionProperties" {
+{abstract} v_RowIndex : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "ICanHandleDataTable" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}

taskt.Core.Automation.Commands.IDataTableRowProperties --|> taskt.Core.Automation.Commands.IDataTableProperties
taskt.Core.Automation.Commands.IDataTableRowProperties --|> taskt.Core.Automation.Commands.IDataTableRowPositionProperties
taskt.Core.Automation.Commands.IDataTableProperties --|> taskt.Core.Automation.Commands.ICanHandleDataTable
taskt.Core.Automation.Commands.IDataTableProperties --|> taskt.Core.Automation.Commands.IExpandableProperties
taskt.Core.Automation.Commands.IDataTableRowPositionProperties --|> taskt.Core.Automation.Commands.IExpandableProperties
taskt.Core.Automation.Commands.ICanHandleDataTable --|> taskt.Core.Automation.Commands.IExpandableProperties
@enduml