@startuml
ReplaceDataTableValueCommand --> ADataTableBothDataTableCommands
ReplaceDataTableValueCommand --> IReplaceValueProperties
ReplaceDataTableValueCommand --> IHaveDataTableElements
ADataTableBothDataTableCommands --> ADataTableInputDataTableCommands
ADataTableInputDataTableCommands --> ScriptCommand
ADataTableInputDataTableCommands --> IDataTableProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml