@startuml
ReplaceDataTableRowValueCommand --> ADataTableRowCommands
ReplaceDataTableRowValueCommand --> IReplaceValueProperties
ReplaceDataTableRowValueCommand --> IHaveDataTableElements
ADataTableRowCommands --> ADataTableInputDataTableCommands
ADataTableRowCommands --> IDataTableRowProperties
ADataTableInputDataTableCommands --> ScriptCommand
ADataTableInputDataTableCommands --> IDataTableProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml