@startuml
ReplaceDataTableColumnValueCommand --> ADataTableColumnCommands
ReplaceDataTableColumnValueCommand --> IReplaceValueProperties
ReplaceDataTableColumnValueCommand --> IHaveDataTableElements
ADataTableColumnCommands --> ADataTableInputDataTableCommands
ADataTableColumnCommands --> IDataTableColumnProperties
ADataTableInputDataTableCommands --> ScriptCommand
ADataTableInputDataTableCommands --> IDataTableProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml