@startuml
frmAddVariable --> DialogLikeThemedForm
frmAddVariable --> DialogLikeThemedForm
DialogLikeThemedForm --> ThemedForm
DialogLikeThemedForm --> ThemedForm
ThemedForm --> Form
ThemedForm --> Form
@enduml