@startuml
EnterKeysFromWindowHandleCommand --> AWindowHandleActionCommands
EnterKeysFromWindowHandleCommand --> IEnterKeysProperties
AWindowHandleActionCommands --> AWindowHandleCommands
AWindowHandleActionCommands --> IWindowHandleActionPropeties
AWindowHandleCommands --> ScriptCommand
AWindowHandleCommands --> IWindowHandleProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml