@startuml
left to right direction
package "taskt.Core.Automation.Commands.KeyMouseGroup"{
Interface "ISendAdvancedKeyStrokesProperties" {
+{abstract} v_KeyActions : DataTable <<get>> <<set>> <<abstract>> 
+{abstract} v_KeyUpDefault : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.KeyMouseGroup"{
Interface "IKeyActionCoreProperties" {
+{abstract} v_WaitTimeAfterKeyEnter : String <<get>> <<set>> <<abstract>> 
+{abstract} v_ActivateCurrentWindow : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IHaveDataTableElements" {
+{abstract} BeforeValidate() : void <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IWindowActivateProperties" {
+{abstract} v_ActivateBeforeAction : String <<get>> <<set>> <<abstract>> 
}
}

taskt.Core.Automation.Commands.KeyMouseGroup.ISendAdvancedKeyStrokesProperties --|> taskt.Core.Automation.Commands.KeyMouseGroup.IKeyActionCoreProperties
taskt.Core.Automation.Commands.KeyMouseGroup.ISendAdvancedKeyStrokesProperties --|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.KeyMouseGroup.IKeyActionCoreProperties --|> taskt.Core.Automation.Commands.IWindowActivateProperties
@enduml