@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
class "FormatDateTimeByUnixTimeCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFormatDateTimeCommands"{
#CommandProcess() : void 
+v_Format : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FormatDateTimeByExcelSerialCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FormatDateTimeByTextCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FormatDateTimeCommand" <<sealed>> {
+RunCommand() : void 
}
}

taskt.Core.Automation.Commands.FormatDateTimeByUnixTimeCommand --|> taskt.Core.Automation.Commands.AFormatDateTimeCommands
taskt.Core.Automation.Commands.FormatDateTimeByExcelSerialCommand --|> taskt.Core.Automation.Commands.AFormatDateTimeCommands
taskt.Core.Automation.Commands.FormatDateTimeByTextCommand --|> taskt.Core.Automation.Commands.AFormatDateTimeCommands
taskt.Core.Automation.Commands.FormatDateTimeCommand --|> taskt.Core.Automation.Commands.AFormatDateTimeCommands
@enduml