@startuml
CalculateDateTimeFromExcelSerialCommand --> ACalculateDateTimeCommands
ACalculateDateTimeCommands --> ADateTimeConvertCommands
ACalculateDateTimeCommands --> IDateTimeResultProperties
ADateTimeConvertCommands --> ScriptCommand
ADateTimeConvertCommands --> IDateTimeConvertProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml