@startuml
ConvertDateTimeToExcelSerialCommand --> ADateTimeConvertCommands
ADateTimeConvertCommands --> ScriptCommand
ADateTimeConvertCommands --> IDateTimeConvertProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml