@startuml
CreateDateTimeFromTextCommand --> ADateTimeCreateCommands
ADateTimeCreateCommands --> ScriptCommand
ADateTimeCreateCommands --> IDateTimeCreateProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml