@startuml
FormatDateTimeByTextCommand --> AFormatDateTimeCommands
AFormatDateTimeCommands --> ADateTimeConvertCommands
ADateTimeConvertCommands --> ScriptCommand
ADateTimeConvertCommands --> IDateTimeConvertProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml