@startuml
package "taskt.Core.Automation.Commands"{
abstract class "ACalculateDateTimeCommands"{
#CommandProcess() : void 
+v_CalculationMethod : String <<get>> <<set>> 
+v_Value : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IDateTimeResultProperties" {
+{abstract} v_Result : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AGetFormattedDateTimeFromCalculatedDateTimeCommands"{
#CommandProcess() : void 
+v_Format : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CalculateDateTimeFromUnixTimeCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CalculateDateTimeFromExcelSerialCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CalculateDateTimeFromTextCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CalculateDateTimeCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFormattedDateTimeFromCalculatedExcelSerialDateTimeCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFormattedDateTimeFromCalculatedUnixDateTimeCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFormattedDateTimeFromCalculatedTextDateTimeCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFormattedDateTimeFromCalculatedDateTimeCommand" <<sealed>> {
+RunCommand() : void 
}
}


taskt.Core.Automation.Commands.IDateTimeResultProperties <|.. taskt.Core.Automation.Commands.ACalculateDateTimeCommands
taskt.Core.Automation.Commands.ACalculateDateTimeCommands <|-- taskt.Core.Automation.Commands.AGetFormattedDateTimeFromCalculatedDateTimeCommands
taskt.Core.Automation.Commands.ACalculateDateTimeCommands <|-- taskt.Core.Automation.Commands.CalculateDateTimeFromUnixTimeCommand
taskt.Core.Automation.Commands.ACalculateDateTimeCommands <|-- taskt.Core.Automation.Commands.CalculateDateTimeFromExcelSerialCommand
taskt.Core.Automation.Commands.ACalculateDateTimeCommands <|-- taskt.Core.Automation.Commands.CalculateDateTimeFromTextCommand
taskt.Core.Automation.Commands.ACalculateDateTimeCommands <|-- taskt.Core.Automation.Commands.CalculateDateTimeCommand
taskt.Core.Automation.Commands.AGetFormattedDateTimeFromCalculatedDateTimeCommands <|-- taskt.Core.Automation.Commands.GetFormattedDateTimeFromCalculatedExcelSerialDateTimeCommand
taskt.Core.Automation.Commands.AGetFormattedDateTimeFromCalculatedDateTimeCommands <|-- taskt.Core.Automation.Commands.GetFormattedDateTimeFromCalculatedUnixDateTimeCommand
taskt.Core.Automation.Commands.AGetFormattedDateTimeFromCalculatedDateTimeCommands <|-- taskt.Core.Automation.Commands.GetFormattedDateTimeFromCalculatedTextDateTimeCommand
taskt.Core.Automation.Commands.AGetFormattedDateTimeFromCalculatedDateTimeCommands <|-- taskt.Core.Automation.Commands.GetFormattedDateTimeFromCalculatedDateTimeCommand
@enduml