@startuml
package "taskt.Core.Automation.Commands"{
abstract class "ADateTimeConvertCommands"{
+v_DateTime : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IDateTimeConvertProperties" {
+{abstract} v_DateTime : String <<get>> <<set>> <<abstract>> 
+{abstract} v_Result : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFormatDateTimeCommands"{
#CommandProcess() : void 
+v_Format : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "ACalculateDateTimeCommands"{
#CommandProcess() : void 
+v_CalculationMethod : String <<get>> <<set>> 
+v_Value : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ConvertDateTimeToUnixTimelCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ConvertDateTimeToExcelSerialCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FormatDateTimeByUnixTimeCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FormatDateTimeByExcelSerialCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FormatDateTimeByTextCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FormatDateTimeCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AGetFormattedDateTimeFromCalculatedDateTimeCommands"{
#CommandProcess() : void 
+v_Format : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CalculateDateTimeFromUnixTimeCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CalculateDateTimeFromExcelSerialCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CalculateDateTimeFromTextCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CalculateDateTimeCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFormattedDateTimeFromCalculatedExcelSerialDateTimeCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFormattedDateTimeFromCalculatedUnixDateTimeCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFormattedDateTimeFromCalculatedTextDateTimeCommand" <<sealed>> {
+RunCommand() : void 
+v_DateTime : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFormattedDateTimeFromCalculatedDateTimeCommand" <<sealed>> {
+RunCommand() : void 
}
}


taskt.Core.Automation.Commands.IDateTimeConvertProperties <|.. taskt.Core.Automation.Commands.ADateTimeConvertCommands
taskt.Core.Automation.Commands.ADateTimeConvertCommands <|-- taskt.Core.Automation.Commands.AFormatDateTimeCommands
taskt.Core.Automation.Commands.ADateTimeConvertCommands <|-- taskt.Core.Automation.Commands.ACalculateDateTimeCommands
taskt.Core.Automation.Commands.ADateTimeConvertCommands <|-- taskt.Core.Automation.Commands.ConvertDateTimeToUnixTimelCommand
taskt.Core.Automation.Commands.ADateTimeConvertCommands <|-- taskt.Core.Automation.Commands.ConvertDateTimeToExcelSerialCommand
taskt.Core.Automation.Commands.AFormatDateTimeCommands <|-- taskt.Core.Automation.Commands.FormatDateTimeByUnixTimeCommand
taskt.Core.Automation.Commands.AFormatDateTimeCommands <|-- taskt.Core.Automation.Commands.FormatDateTimeByExcelSerialCommand
taskt.Core.Automation.Commands.AFormatDateTimeCommands <|-- taskt.Core.Automation.Commands.FormatDateTimeByTextCommand
taskt.Core.Automation.Commands.AFormatDateTimeCommands <|-- taskt.Core.Automation.Commands.FormatDateTimeCommand
taskt.Core.Automation.Commands.ACalculateDateTimeCommands <|-- taskt.Core.Automation.Commands.AGetFormattedDateTimeFromCalculatedDateTimeCommands
taskt.Core.Automation.Commands.ACalculateDateTimeCommands <|-- taskt.Core.Automation.Commands.CalculateDateTimeFromUnixTimeCommand
taskt.Core.Automation.Commands.ACalculateDateTimeCommands <|-- taskt.Core.Automation.Commands.CalculateDateTimeFromExcelSerialCommand
taskt.Core.Automation.Commands.ACalculateDateTimeCommands <|-- taskt.Core.Automation.Commands.CalculateDateTimeFromTextCommand
taskt.Core.Automation.Commands.ACalculateDateTimeCommands <|-- taskt.Core.Automation.Commands.CalculateDateTimeCommand
taskt.Core.Automation.Commands.AGetFormattedDateTimeFromCalculatedDateTimeCommands <|-- taskt.Core.Automation.Commands.GetFormattedDateTimeFromCalculatedExcelSerialDateTimeCommand
taskt.Core.Automation.Commands.AGetFormattedDateTimeFromCalculatedDateTimeCommands <|-- taskt.Core.Automation.Commands.GetFormattedDateTimeFromCalculatedUnixDateTimeCommand
taskt.Core.Automation.Commands.AGetFormattedDateTimeFromCalculatedDateTimeCommands <|-- taskt.Core.Automation.Commands.GetFormattedDateTimeFromCalculatedTextDateTimeCommand
taskt.Core.Automation.Commands.AGetFormattedDateTimeFromCalculatedDateTimeCommands <|-- taskt.Core.Automation.Commands.GetFormattedDateTimeFromCalculatedDateTimeCommand
@enduml