@startuml
package "taskt.Core.Automation.Commands"{
class "ExcelGetRowValuesAsDictionaryCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AExcelRowRangeGetCommands"{
+{abstract} v_Result : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExcelGetRowValuesAsDataTableCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExcelGetRowValuesAsListCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Commands.AExcelRowRangeGetCommands <|-- taskt.Core.Automation.Commands.ExcelGetRowValuesAsDictionaryCommand
taskt.Core.Automation.Commands.AExcelRowRangeGetCommands <|-- taskt.Core.Automation.Commands.ExcelGetRowValuesAsDataTableCommand
taskt.Core.Automation.Commands.AExcelRowRangeGetCommands <|-- taskt.Core.Automation.Commands.ExcelGetRowValuesAsListCommand
@enduml