@startuml
package "taskt.Core.Automation.Commands"{
class "ExcelSetRowValuesFromDataTableCommand" <<sealed>> {
+RunCommand() : void 
+v_DataTableVariable : String <<get>> <<set>> 
+v_DataTableRowIndex : String <<get>> <<set>> 
+v_WhenItemNotEnough : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AExcelRowRangeSetCommands"{
+{abstract} v_WhenItemNotEnough : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExcelSetRowValuesFromDictionaryCommand" <<sealed>> {
+RunCommand() : void 
+v_DictionaryVariable : String <<get>> <<set>> 
+v_WhenItemNotEnough : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExcelSetRowValuesFromListCommand" <<sealed>> {
+RunCommand() : void 
+v_ListVariable : String <<get>> <<set>> 
+v_WhenItemNotEnough : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Commands.AExcelRowRangeSetCommands <|-- taskt.Core.Automation.Commands.ExcelSetRowValuesFromDataTableCommand
taskt.Core.Automation.Commands.AExcelRowRangeSetCommands <|-- taskt.Core.Automation.Commands.ExcelSetRowValuesFromDictionaryCommand
taskt.Core.Automation.Commands.AExcelRowRangeSetCommands <|-- taskt.Core.Automation.Commands.ExcelSetRowValuesFromListCommand
@enduml