@startuml
ExcelGetRangeValuesAsDataTableCommand --> AExcelColumnRowRangeGetCommands
ExcelGetRangeValuesAsDataTableCommand --> IDataTableResultProperties
AExcelColumnRowRangeGetCommands --> AExcelColumnRowRangeCommands
AExcelColumnRowRangeGetCommands --> IExcelColumnRowRangeGetProperties
AExcelColumnRowRangeCommands --> AExcelInstanceCommands
AExcelColumnRowRangeCommands --> IExcelColumnRowRangeProperties
AExcelInstanceCommands --> ScriptCommand
AExcelInstanceCommands --> IExcelInstanceProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml