@startuml
ExcelGoToCellCommand --> AExcelCellCommands
AExcelCellCommands --> AExcelInstanceCommands
AExcelCellCommands --> IExcelCellProperties
AExcelInstanceCommands --> ScriptCommand
AExcelInstanceCommands --> IExcelInstanceProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml