@startuml
ExcelGetRowValuesAsDataTableCommand --> AExcelRowRangeGetCommands
ExcelGetRowValuesAsDataTableCommand --> IDataTableResultProperties
AExcelRowRangeGetCommands --> AExcelRowRangeCommands
AExcelRowRangeGetCommands --> IExcelRowRangeGetProperties
AExcelRowRangeCommands --> AExcelInstanceCommands
AExcelRowRangeCommands --> IExcelRowRangeProperties
AExcelInstanceCommands --> ScriptCommand
AExcelInstanceCommands --> IExcelInstanceProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml