@startuml
ExcelGetExcelInformationCommand --> AExcelInstanceCommands
AExcelInstanceCommands --> ScriptCommand
AExcelInstanceCommands --> IExcelInstanceProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml