@startuml
ExcelDeleteCellCommand --> AExcelInstanceCommands
AExcelInstanceCommands --> ScriptCommand
AExcelInstanceCommands --> IExcelInstanceProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml