@startuml
ExcelCopyWorksheetCommand --> AExcelInstanceCommands
ExcelCopyWorksheetCommand --> IExcelWorksheetCopyRenameProperties
AExcelInstanceCommands --> ScriptCommand
AExcelInstanceCommands --> IExcelInstanceProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml