@startuml
ExcelGetColumnValuesAsDataTableCommand --> AExcelColumnRangeGetCommands
ExcelGetColumnValuesAsDataTableCommand --> IDataTableResultProperties
AExcelColumnRangeGetCommands --> AExcelColumnRangeCommands
AExcelColumnRangeGetCommands --> IExcelColumnRangeGetProperties
AExcelColumnRangeCommands --> AExcelInstanceCommands
AExcelColumnRangeCommands --> IExcelColumnRangeProperties
AExcelInstanceCommands --> ScriptCommand
AExcelInstanceCommands --> IExcelInstanceProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml