@startuml
package "taskt.Core.Automation.Commands"{
abstract class "AExcelSheetCommands"{
+v_SheetName : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExcelWorksheetProperties" {
+{abstract} v_SheetName : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExcelCheckWorksheetExistsCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExcelGetWorksheetInformationCommand" <<sealed>> {
+RunCommand() : void 
+v_InfoType : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExcelGetWorksheetsCommand" <<sealed>> {
+RunCommand() : void 
+v_SheetName : String <<get>> <<set>> 
+v_CompareMethod : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExcelDeleteWorksheetCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "ExcelAddWorksheetCommand" <<sealed>> {
+RunCommand() : void 
+v_SheetName : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExcelActivateWorksheetCommand" <<sealed>> {
+RunCommand() : void 
}
}


taskt.Core.Automation.Commands.IExcelWorksheetProperties <|.. taskt.Core.Automation.Commands.AExcelSheetCommands
taskt.Core.Automation.Commands.AExcelSheetCommands <|-- taskt.Core.Automation.Commands.ExcelCheckWorksheetExistsCommand
taskt.Core.Automation.Commands.AExcelSheetCommands <|-- taskt.Core.Automation.Commands.ExcelGetWorksheetInformationCommand
taskt.Core.Automation.Commands.AExcelSheetCommands <|-- taskt.Core.Automation.Commands.ExcelGetWorksheetsCommand
taskt.Core.Automation.Commands.AExcelSheetCommands <|-- taskt.Core.Automation.Commands.ExcelDeleteWorksheetCommand
taskt.Core.Automation.Commands.AExcelSheetCommands <|-- taskt.Core.Automation.Commands.ExcelAddWorksheetCommand
taskt.Core.Automation.Commands.AExcelSheetCommands <|-- taskt.Core.Automation.Commands.ExcelActivateWorksheetCommand
@enduml