@startuml
BeginMultiIfCommand --> ScriptCommand
BeginMultiIfCommand --> IHaveDataTableElements
BeginMultiIfCommand --> IHaveIfAdditionalCommands
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml