@startuml
BeginIfCommand --> ScriptCommand
BeginIfCommand --> IHaveDataTableElements
BeginIfCommand --> IHaveIfAdditionalCommands
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml