@startuml
package "taskt.Core.Automation.Commands"{
Interface "IHaveIfAdditionalCommands" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "IHaveAdditionalCommands" {
}
}


taskt.Core.Automation.Commands.IHaveAdditionalCommands <|-- taskt.Core.Automation.Commands.IHaveIfAdditionalCommands
@enduml