@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
class "SequenceCommand" <<sealed>> {
+RunCommand() : void 
+GetDisplayValue() : String
+v_scriptActions : List<taskt.Core.Automation.Commands.ScriptCommand>
}
}

package "taskt.Core.Automation.Commands"{
Interface "IHaveSequenceAdditionalCommands" {
}
}

taskt.Core.Automation.Commands.SequenceCommand ..|> taskt.Core.Automation.Commands.IHaveSequenceAdditionalCommands
@enduml