@startuml
package "taskt.Core.Automation.Commands"{
Interface "IHaveSequenceAdditionalCommands" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "IHaveAdditionalCommands" {
}
}


taskt.Core.Automation.Commands.IHaveAdditionalCommands <|-- taskt.Core.Automation.Commands.IHaveSequenceAdditionalCommands
@enduml