@startuml
CopyFolderCommand --> AFolderCopyMoveFolderCommands
CopyFolderCommand --> IFolderCopyFolderProperties
AFolderCopyMoveFolderCommands --> AFolderExistsFolderBeforeAfterResultCommands
AFolderExistsFolderBeforeAfterResultCommands --> AFolderExistsFolderPathCommands
AFolderExistsFolderBeforeAfterResultCommands --> IFolderExistsFolderPathBeforeAfterPathResultProperties
AFolderExistsFolderPathCommands --> AFolderFolderPathCommands
AFolderExistsFolderPathCommands --> IFolderExistsFolderPathProperties
AFolderFolderPathCommands --> ScriptCommand
AFolderFolderPathCommands --> IFolderPathProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml