@startuml
CreateFolderByPathCommand --> AFolderFolderPathCommands
AFolderFolderPathCommands --> ScriptCommand
AFolderFolderPathCommands --> IFolderPathProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml