@startuml
CreateFolderCommand --> AFolderExistsFolderPathPathResultCommands
CreateFolderCommand --> ICanHandleFolderName
AFolderExistsFolderPathPathResultCommands --> AFolderExistsFolderPathCommands
AFolderExistsFolderPathPathResultCommands --> IFolderExistsFolderPathPathResultProperties
AFolderExistsFolderPathCommands --> AFolderFolderPathCommands
AFolderExistsFolderPathCommands --> IFolderExistsFolderPathProperties
AFolderFolderPathCommands --> ScriptCommand
AFolderFolderPathCommands --> IFolderPathProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml