@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
Interface "ICanHandleFolderPath" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "ICanHandleFileOrFolderPath" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}

taskt.Core.Automation.Commands.ICanHandleFolderPath --|> taskt.Core.Automation.Commands.ICanHandleFileOrFolderPath
taskt.Core.Automation.Commands.ICanHandleFileOrFolderPath --|> taskt.Core.Automation.Commands.IExpandableProperties
@enduml