@startuml
package "taskt.Core.Automation.Commands"{
abstract class "AFolderFolderPathCommands"{
+v_TargetFolderPath : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IFolderPathProperties" {
+{abstract} v_TargetFolderPath : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IFolderExistsFolderPathProperties" {
+{abstract} v_WaitTimeForFolder : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFolderExistsFolderPathCommands"{
+v_WaitTimeForFolder : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CreateFolderByPathCommand" <<sealed>> {
+RunCommand() : void 
+v_WhenFolderExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExtractionFolderPathCommand" <<sealed>> {
+RunCommand() : void 
-lnkFormatChecker_Click() : void 
+v_Format : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IFolderExistsFolderPathBeforeAfterPathResultProperties" {
+{abstract} v_BeforeFolderPathResult : String <<get>> <<set>> <<abstract>> 
+{abstract} v_AfterFolderPathResult : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IFolderExistsFolderPathPathResultProperties" {
+{abstract} v_ResultPath : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetRandomFilePathCommand" {
+RunCommand() : void 
+v_TargetFolderPath : String <<get>> <<set>> 
+v_Extension : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_CheckFileDoesNotExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFileNumberedFileCommands"{
#SearchNonExistentFileAction() : void 
+v_TargetFolderPath : String <<get>> <<set>> 
+v_BeforeFileCounter : String <<get>> <<set>> 
+v_Digits : String <<get>> <<set>> 
+v_AfterFileCounter : String <<get>> <<set>> 
+v_Extension : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_StartValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFolderExistsFolderBeforeAfterResultCommands"{
+v_BeforeFolderPathResult : String <<get>> <<set>> 
+v_AfterFolderPathResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFolderExistsFolderPathPathResultCommands"{
+v_ResultPath : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFilesPathAsListCommand" <<sealed>> {
+RunCommand() : void 
+v_SearchFileName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
+v_SearchExtension : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFoldersPathAsListCommand" <<sealed>> {
+RunCommand() : void 
+v_SearchFolderName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetLastExistentNumberedFilePathCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "GetNonExistentFilePathCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFolderCopyMoveFolderCommands"{
#CreateActionFunc() : Func
+v_DestinationFolderPath : String <<get>> <<set>> 
+v_CreateDirectory : String <<get>> <<set>> 
+v_WhenDestinationIsSame : String <<get>> <<set>> 
+v_WhenDestinationExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFolderCopySameRenameFolderCommands"{
#CreateActionFunc() : Func
+v_NewFolderName : String <<get>> <<set>> 
+v_WhenFolderNameSame : String <<get>> <<set>> 
+v_WhenDestinationExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "OpenFolderCommand" <<sealed>> {
+RunCommand() : void 
+v_WaitTimeForOpen : String <<get>> <<set>> 
+v_WindowNameResult : String <<get>> <<set>> 
+v_WindowHandleResult : String <<get>> <<set>> 
+v_WaitTimeForFolder : String <<get>> <<set>> 
-ExplorerProcessName : string
}
}

package "taskt.Core.Automation.Commands"{
class "GetRandomFolderPathCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_CheckFolderDoesNotExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "WaitForFolderToExistCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "CheckFolderExistsCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForFolder : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CreateFolderCommand" <<sealed>> {
+RunCommand() : void 
+v_NewFolderName : String <<get>> <<set>> 
+v_WhenFolderExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "DeleteFolderCommand" <<sealed>> {
+RunCommand() : void 
+v_MoveToRecycleBin : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CopyFolderCommand" <<sealed>> {
+RunCommand() : void 
+v_CopySubFolder : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "MoveFolderCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "CopyFolderInSamLocationCommand" <<sealed>> {
+RunCommand() : void 
+v_CopySubFolder : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "RenameFolderCommand" <<sealed>> {
+RunCommand() : void 
}
}


taskt.Core.Automation.Commands.IFolderPathProperties <|.. taskt.Core.Automation.Commands.AFolderFolderPathCommands
taskt.Core.Automation.Commands.IFolderPathProperties <|-- taskt.Core.Automation.Commands.IFolderExistsFolderPathProperties
taskt.Core.Automation.Commands.AFolderFolderPathCommands <|-- taskt.Core.Automation.Commands.AFolderExistsFolderPathCommands
taskt.Core.Automation.Commands.AFolderFolderPathCommands <|-- taskt.Core.Automation.Commands.CreateFolderByPathCommand
taskt.Core.Automation.Commands.AFolderFolderPathCommands <|-- taskt.Core.Automation.Commands.ExtractionFolderPathCommand
taskt.Core.Automation.Commands.IFolderExistsFolderPathProperties <|.. taskt.Core.Automation.Commands.AFolderExistsFolderPathCommands
taskt.Core.Automation.Commands.IFolderExistsFolderPathProperties <|-- taskt.Core.Automation.Commands.IFolderExistsFolderPathBeforeAfterPathResultProperties
taskt.Core.Automation.Commands.IFolderExistsFolderPathProperties <|-- taskt.Core.Automation.Commands.IFolderExistsFolderPathPathResultProperties
taskt.Core.Automation.Commands.AFolderExistsFolderPathCommands <|-- taskt.Core.Automation.Commands.GetRandomFilePathCommand
taskt.Core.Automation.Commands.AFolderExistsFolderPathCommands <|-- taskt.Core.Automation.Commands.AFileNumberedFileCommands
taskt.Core.Automation.Commands.AFolderExistsFolderPathCommands <|-- taskt.Core.Automation.Commands.AFolderExistsFolderBeforeAfterResultCommands
taskt.Core.Automation.Commands.AFolderExistsFolderPathCommands <|-- taskt.Core.Automation.Commands.AFolderExistsFolderPathPathResultCommands
taskt.Core.Automation.Commands.AFolderExistsFolderPathCommands <|-- taskt.Core.Automation.Commands.GetFilesPathAsListCommand
taskt.Core.Automation.Commands.AFolderExistsFolderPathCommands <|-- taskt.Core.Automation.Commands.GetFoldersPathAsListCommand
taskt.Core.Automation.Commands.IFolderExistsFolderPathBeforeAfterPathResultProperties <|.. taskt.Core.Automation.Commands.AFolderExistsFolderBeforeAfterResultCommands
taskt.Core.Automation.Commands.IFolderExistsFolderPathPathResultProperties <|.. taskt.Core.Automation.Commands.AFolderExistsFolderPathPathResultCommands
taskt.Core.Automation.Commands.AFileNumberedFileCommands <|-- taskt.Core.Automation.Commands.GetLastExistentNumberedFilePathCommand
taskt.Core.Automation.Commands.AFileNumberedFileCommands <|-- taskt.Core.Automation.Commands.GetNonExistentFilePathCommand
taskt.Core.Automation.Commands.AFolderExistsFolderBeforeAfterResultCommands <|-- taskt.Core.Automation.Commands.AFolderCopyMoveFolderCommands
taskt.Core.Automation.Commands.AFolderExistsFolderBeforeAfterResultCommands <|-- taskt.Core.Automation.Commands.AFolderCopySameRenameFolderCommands
taskt.Core.Automation.Commands.AFolderExistsFolderPathPathResultCommands <|-- taskt.Core.Automation.Commands.OpenFolderCommand
taskt.Core.Automation.Commands.AFolderExistsFolderPathPathResultCommands <|-- taskt.Core.Automation.Commands.GetRandomFolderPathCommand
taskt.Core.Automation.Commands.AFolderExistsFolderPathPathResultCommands <|-- taskt.Core.Automation.Commands.WaitForFolderToExistCommand
taskt.Core.Automation.Commands.AFolderExistsFolderPathPathResultCommands <|-- taskt.Core.Automation.Commands.CheckFolderExistsCommand
taskt.Core.Automation.Commands.AFolderExistsFolderPathPathResultCommands <|-- taskt.Core.Automation.Commands.CreateFolderCommand
taskt.Core.Automation.Commands.AFolderExistsFolderPathPathResultCommands <|-- taskt.Core.Automation.Commands.DeleteFolderCommand
taskt.Core.Automation.Commands.AFolderCopyMoveFolderCommands <|-- taskt.Core.Automation.Commands.CopyFolderCommand
taskt.Core.Automation.Commands.AFolderCopyMoveFolderCommands <|-- taskt.Core.Automation.Commands.MoveFolderCommand
taskt.Core.Automation.Commands.AFolderCopySameRenameFolderCommands <|-- taskt.Core.Automation.Commands.CopyFolderInSamLocationCommand
taskt.Core.Automation.Commands.AFolderCopySameRenameFolderCommands <|-- taskt.Core.Automation.Commands.RenameFolderCommand
@enduml