@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
Interface "IFolderCopyFolderProperties" {
+{abstract} v_CopySubFolder : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}

taskt.Core.Automation.Commands.IFolderCopyFolderProperties --|> taskt.Core.Automation.Commands.IExpandableProperties
@enduml