@startuml
package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchChildUIElementFromUIElementByXPathCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AChildrenSearchUIElementsFromUIElementByXPathCommands"{
+v_TargetElement : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByXPathCommands <|-- taskt.Core.Automation.Commands.UIAutomationSearchChildUIElementFromUIElementByXPathCommand
@enduml