@startuml
AChildrenSearchUIElementsFromSomethingByXPathCommands --> ScriptCommand
AChildrenSearchUIElementsFromSomethingByXPathCommands --> IUIElementChildrenSearchXPathProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml