@startuml
ADescendantsSearchUIElementsFromSomethingByXPathCommands --> AChildrenSearchUIElementsFromSomethingByXPathCommands
ADescendantsSearchUIElementsFromSomethingByXPathCommands --> IUIElementDescendantsSearchXPathProperties
AChildrenSearchUIElementsFromSomethingByXPathCommands --> ScriptCommand
AChildrenSearchUIElementsFromSomethingByXPathCommands --> IUIElementChildrenSearchXPathProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml