@startuml
package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands"{
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands <|-- taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromWindowHandleCommand
@enduml