@startuml
left to right direction
package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands"{
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands"{
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsInformationFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsInformationFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands
@enduml