@startuml
ADoSomethingUIElementCommands --> AUIElementCoreCommands
ADoSomethingUIElementCommands --> IDoSomethingUIElementProperties
AUIElementCoreCommands --> ScriptCommand
AUIElementCoreCommands --> IUIElementCoreProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml