@startuml
package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADoSomethingUIElementCommands"{
+v_WindowNameResult : String <<get>> <<set>> 
+v_WindowHandleResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementCoreCommands"{
+v_TargetElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AGetFromUIElementCommands"{
+v_WhenValueCanNotRetrieved : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionCommands"{
+v_ActivateWindowBeforeAction : String <<get>> <<set>> 
+v_WaitTimeBeforeAction : String <<get>> <<set>> 
+v_WaitTimeAfterAction : String <<get>> <<set>> 
+v_WhenActionIsNotSupported : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchChildrenUIElementsTreeXMLFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsTreeXMLFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
+v_MaxDepth : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetTextsFromTableUIElementAsDataTableCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetWindowUIElementFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetTableInformationFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_InformationType : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_ContainsHeader : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetScrollBarInformationFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_InformationType : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetWindowHandleFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowHandleResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetWindowNameFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowNameResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetPropertyValueFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_PropertyName : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_WhenValueCanNotRetrieved : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetUIElementPositionCommand" <<sealed>> {
+RunCommand() : void 
+v_XPosition : String <<get>> <<set>> 
+v_YPosition : String <<get>> <<set>> 
+v_PositionBase : String <<get>> <<set>> 
+v_CoordinateReference : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetUIElementSizeCommand" <<sealed>> {
+RunCommand() : void 
+v_Width : String <<get>> <<set>> 
+v_Height : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetSelectedStateFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetUIElementFromTableUIElementCommand" <<sealed>> {
+RunCommand() : void 
-{static} GetInRangeUIElement() : AutomationElement
+v_Row : String <<get>> <<set>> 
+v_Column : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetSelectionItemsValueFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_ExpandWhenItemsNotFound : String <<get>> <<set>> 
+v_WaitTimeAfterExpand : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetTextFromTableUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Row : String <<get>> <<set>> 
+v_Column : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetTextFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetParentUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationScrollPercentUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_ScrollBarType : String <<get>> <<set>> 
+v_ScrollValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSetSelectedStateToUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_State : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationClickUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_ClickType : String <<get>> <<set>> 
+v_XOffset : String <<get>> <<set>> 
+v_YOffset : String <<get>> <<set>> 
+v_ActivateWindowBeforeAction : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationExpandCollapseItemsInUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_ItemsState : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationScrollUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_ScrollBarType : String <<get>> <<set>> 
+v_DirectionAndAmount : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSelectItemInUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Item : String <<get>> <<set>> 
+v_ItemValueType : String <<get>> <<set>> 
+v_ExpandWhenItemsNotFound : String <<get>> <<set>> 
+v_WaitTimeAfterExpand : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSelectUIElementCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSetTextToUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_TextToSet : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementCoreCommands <|-- taskt.Core.Automation.Commands.UIAutomationGroup.ADoSomethingUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADoSomethingUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADoSomethingUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADoSomethingUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationSearchChildrenUIElementsTreeXMLFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.ADoSomethingUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationSearchUIElementsTreeXMLFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetTextsFromTableUIElementAsDataTableCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetWindowUIElementFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetTableInformationFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetScrollBarInformationFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetWindowHandleFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetWindowNameFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetPropertyValueFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetUIElementPositionCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetUIElementSizeCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetSelectedStateFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetUIElementFromTableUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetSelectionItemsValueFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetTextFromTableUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetTextFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands <|-- taskt.Core.Automation.Commands.UIAutomationGetParentUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands <|-- taskt.Core.Automation.Commands.UIAutomationScrollPercentUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands <|-- taskt.Core.Automation.Commands.UIAutomationSetSelectedStateToUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands <|-- taskt.Core.Automation.Commands.UIAutomationClickUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands <|-- taskt.Core.Automation.Commands.UIAutomationExpandCollapseItemsInUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands <|-- taskt.Core.Automation.Commands.UIAutomationScrollUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands <|-- taskt.Core.Automation.Commands.UIAutomationSelectItemInUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands <|-- taskt.Core.Automation.Commands.UIAutomationSelectUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands <|-- taskt.Core.Automation.Commands.UIAutomationSetTextToUIElementCommand
@enduml