@startuml
AUIElementActionFromSomethingByXPathCommands --> AUIElementActionSomewayCommands
AUIElementActionFromSomethingByXPathCommands --> IUIElementChildrenSearchXPathProperties
AUIElementActionFromSomethingByXPathCommands --> IUIElementDescendantsSearchXPathProperties
AUIElementActionSomewayCommands --> ScriptCommand
AUIElementActionSomewayCommands --> IUIElementUIElementActionSomewayProperties
AUIElementActionSomewayCommands --> IFromWindowNameResultsProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml