@startuml
AUIElementActionSomewayCommands --> ScriptCommand
AUIElementActionSomewayCommands --> IUIElementUIElementActionSomewayProperties
AUIElementActionSomewayCommands --> IFromWindowNameResultsProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml