@startuml
package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "ICanHandleUIElementXML" {
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "ICanHandleUIElement" {
}
}


taskt.Core.Automation.Commands.UIAutomationGroup.ICanHandleUIElement <|-- taskt.Core.Automation.Commands.UIAutomationGroup.ICanHandleUIElementXML
@enduml