@startuml
left to right direction
package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IGetUIElementsInformationProperties" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "IResultProperties" {
+{abstract} v_Result : String <<get>> <<set>> <<abstract>> 
}
}

taskt.Core.Automation.Commands.UIAutomationGroup.IGetUIElementsInformationProperties --|> taskt.Core.Automation.Commands.IResultProperties
@enduml