@startuml
left to right direction
package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionSomewayCommands"{
#UIElementActionProcess() : void 
+AfterShown() : void 
#cmbActionType_SelectedItemChange() : void 
#{static} AddDataTableRows() : void 
#{static} SetComboBoxParameterProcess() : void 
#{static} ApplyDGVCombBox() : void 
#{static} CreateDGVComboBox() : DataGridViewComboBoxCell
+BeforeValidate() : void 
+{abstract} v_AutomationType : String <<get>> <<set>> <<abstract>> 
+{abstract} v_UIAActionParameters : DataTable <<get>> <<set>> <<abstract>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
+v_MaxDepth : String <<get>> <<set>> 
+v_TargetUIElement : String <<get>> <<set>> 
+v_WindowNameResult : String <<get>> <<set>> 
+v_WindowHandleResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementUIElementActionSomewayProperties" {
+{abstract} v_AutomationType : String <<get>> <<set>> <<abstract>> 
+{abstract} v_UIAActionParameters : DataTable <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromSomethingByTreeWalkerCommands"{
+v_SearchParameters : DataTable <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
+v_AutomationType : String <<get>> <<set>> 
+v_UIAActionParameters : DataTable <<get>> <<set>> 
+v_MaxNumberUIElements : String <<get>> <<set>> 
+v_SiblingsDirection : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromSomethingByXPathCommands"{
+v_AutomationType : String <<get>> <<set>> 
+v_SearchXPath : String <<get>> <<set>> 
+v_UIAActionParameters : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromWindowSomethingByTreeWalkerCommands"{
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromWindowSomethingByXPathCommands"{
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
-MatchMethodComboBox_SelectionChangeCommitted() : void 
+Refresh() : void 
+v_WindowName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_WindowSelectionMethod : String <<get>> <<set>> 
+v_TargetWindowIndex : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
-MatchMethodComboBox_SelectionChangeCommitted() : void 
+Refresh() : void 
+v_WindowName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetWindowIndex : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
}
}

taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionSomewayCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementUIElementActionSomewayProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionSomewayCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByXPathCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionSomewayCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByXPathCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowNameCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowNameCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByXPathCommands
@enduml