@startuml
package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands"{
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
+v_MaxNumberUIElements : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementDescendantsSearchAnyUIElementProperties" {
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromSomethingByTreeWalkerCommands"{
+v_SearchParameters : DataTable <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
+v_AutomationType : String <<get>> <<set>> 
+v_UIAActionParameters : DataTable <<get>> <<set>> 
+v_MaxNumberUIElements : String <<get>> <<set>> 
+v_SiblingsDirection : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands"{
+v_TargetElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromWindowSomethingByTreeWalkerCommands"{
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationWaitForUIElementToExistsCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationCheckUIElementExistsCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
-MatchMethodComboBox_SelectionChangeCommitted() : void 
+Refresh() : void 
+v_WindowName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_WindowSelectionMethod : String <<get>> <<set>> 
+v_TargetWindowIndex : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchAnyUIElementProperties <|.. taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchAnyUIElementProperties <|.. taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands <|-- taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands <|-- taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands <|-- taskt.Core.Automation.Commands.UIAutomationWaitForUIElementToExistsCommand
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands <|-- taskt.Core.Automation.Commands.UIAutomationCheckUIElementExistsCommand
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands <|-- taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromUIElementCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands <|-- taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowHandleCommand
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands <|-- taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowNameCommand
@enduml