@startuml
left to right direction
package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IGetUIElementsXMLTreeFromSomethingProperties" {
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementWindowResultsFromUIElementProperties" {
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementChildrenSearchSomewayProperties" {
+{abstract} v_WaitTimeForUIElement : String <<get>> <<set>> <<abstract>> 
+{abstract} v_MaxSiblings : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IDoSomethingUIElementProperties" {
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsTreeXMLFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
+v_MaxDepth : String <<get>> <<set>> 
+v_WindowHandleResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsTreeXMLFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
+v_MaxDepth : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsTreeXMLFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
+v_MaxDepth : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementChildrenSearchXPathProperties" {
+{abstract} v_SearchXPath : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementChildrenSearchParametersProperties" {
+{abstract} v_SearchParameters : DataTable <<get>> <<set>> <<abstract>> 
+{abstract} v_MaxNumberUIElements : String <<get>> <<set>> <<abstract>> 
+{abstract} v_SiblingsDirection : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchChildrenUIElementsTreeXMLFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands"{
+v_TargetElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AChildrenSearchUIElementsFromUIElementByXPathCommands"{
+v_TargetElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands"{
+v_TargetElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADoSomethingUIElementCommands"{
+v_WindowNameResult : String <<get>> <<set>> 
+v_WindowHandleResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IGetFromUIElementProperties" {
+{abstract} v_WhenValueCanNotRetrieved : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementActionProperties" {
+{abstract} v_WaitTimeBeforeAction : String <<get>> <<set>> <<abstract>> 
+{abstract} v_WaitTimeAfterAction : String <<get>> <<set>> <<abstract>> 
+{abstract} v_ActivateWindowBeforeAction : String <<get>> <<set>> <<abstract>> 
+{abstract} v_WhenActionIsNotSupported : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementSelectionItemsProperties" {
+{abstract} v_ExpandWhenItemsNotFound : String <<get>> <<set>> <<abstract>> 
+{abstract} v_WaitTimeAfterExpand : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AChildrenSearchUIElementsFromSomethingByXPathCommands"{
+v_SearchXPath : String <<get>> <<set>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
+v_WindowNameResult : String <<get>> <<set>> 
+v_WindowHandleResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromSomethingByXPathCommands"{
+v_AutomationType : String <<get>> <<set>> 
+v_SearchXPath : String <<get>> <<set>> 
+v_UIAActionParameters : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementDescendantsSearchXPathProperties" {
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands"{
+AfterShown() : void 
+BeforeValidate() : void 
+v_SearchParameters : DataTable <<get>> <<set>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
+v_MaxNumberUIElements : String <<get>> <<set>> 
+v_SiblingsDirection : String <<get>> <<set>> 
+v_WindowNameResult : String <<get>> <<set>> 
+v_WindowHandleResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromSomethingByTreeWalkerCommands"{
+v_SearchParameters : DataTable <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
+v_AutomationType : String <<get>> <<set>> 
+v_UIAActionParameters : DataTable <<get>> <<set>> 
+v_MaxNumberUIElements : String <<get>> <<set>> 
+v_SiblingsDirection : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementDescendantsSearchParametersProperties" {
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchChildrenUIElementsInformationCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchChildUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchChildUIElementFromUIElementByXPathCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationWaitForUIElementToExistsCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationCheckUIElementExistsCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AGetFromUIElementCommands"{
+v_WhenValueCanNotRetrieved : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionCommands"{
+v_ActivateWindowBeforeAction : String <<get>> <<set>> 
+v_WaitTimeBeforeAction : String <<get>> <<set>> 
+v_WaitTimeAfterAction : String <<get>> <<set>> 
+v_WhenActionIsNotSupported : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetSelectionItemsValueFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_ExpandWhenItemsNotFound : String <<get>> <<set>> 
+v_WaitTimeAfterExpand : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSelectItemInUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Item : String <<get>> <<set>> 
+v_ItemValueType : String <<get>> <<set>> 
+v_ExpandWhenItemsNotFound : String <<get>> <<set>> 
+v_WaitTimeAfterExpand : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchUIElementsFromSomethingByXPathCommands"{
+v_MaxDepth : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromWindowSomethingByXPathCommands"{
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands"{
+v_MaxDepth : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromWindowSomethingByTreeWalkerCommands"{
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementDescendantsSearchAnyUIElementProperties" {
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetTextsFromTableUIElementAsDataTableCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetWindowUIElementFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetTableInformationFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_InformationType : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_ContainsHeader : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetScrollBarInformationFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_InformationType : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetWindowHandleFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowHandleResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetWindowNameFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowNameResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetPropertyValueFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_PropertyName : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_WhenValueCanNotRetrieved : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetUIElementPositionCommand" <<sealed>> {
+RunCommand() : void 
+v_XPosition : String <<get>> <<set>> 
+v_YPosition : String <<get>> <<set>> 
+v_PositionBase : String <<get>> <<set>> 
+v_CoordinateReference : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetUIElementSizeCommand" <<sealed>> {
+RunCommand() : void 
+v_Width : String <<get>> <<set>> 
+v_Height : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetSelectedStateFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetUIElementFromTableUIElementCommand" <<sealed>> {
+RunCommand() : void 
-{static} GetInRangeUIElement() : AutomationElement
+v_Row : String <<get>> <<set>> 
+v_Column : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetTextFromTableUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Row : String <<get>> <<set>> 
+v_Column : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetTextFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationGetParentUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationScrollPercentUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_ScrollBarType : String <<get>> <<set>> 
+v_ScrollValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSetSelectedStateToUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_State : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationClickUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_ClickType : String <<get>> <<set>> 
+v_XOffset : String <<get>> <<set>> 
+v_YOffset : String <<get>> <<set>> 
+v_ActivateWindowBeforeAction : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationExpandCollapseItemsInUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_ItemsState : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationScrollUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_ScrollBarType : String <<get>> <<set>> 
+v_DirectionAndAmount : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSelectUIElementCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSetTextToUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_TextToSet : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchUIElementsFromUIElementByXPathCommands"{
+v_TargetElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchUIElementsFromWindowHandleByXPathCommands"{
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchUIElementsFromWindowNameByXPathCommands"{
#MatchMethodComboBox_SelectionChangeCommitted() : void 
+Refresh() : void 
#SearchWindowAfterAction() : void 
+v_WindowName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetWindowIndex : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_WindowUIElement : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
-MatchMethodComboBox_SelectionChangeCommitted() : void 
+Refresh() : void 
+v_WindowName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetWindowIndex : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands"{
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
+v_MaxNumberUIElements : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands"{
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "ADescendantsSearchUIElementsFromWindowNameByTreeWalkerCommands"{
#MatchMethodComboBox_SelectionChangeCommitted() : void 
+Refresh() : void 
#SearchWindowAfterAction() : void 
+v_WindowName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetWindowIndex : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_WindowUIElement : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsInformationFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_TargetElement : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
-MatchMethodComboBox_SelectionChangeCommitted() : void 
+Refresh() : void 
+v_WindowName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_WindowSelectionMethod : String <<get>> <<set>> 
+v_TargetWindowIndex : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationCheckUIElementExistsByXPathCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationWaitForUIElementToExistsByXPathCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromUIElementByXPathCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromWindowHandleByXPathCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromWindowNameByXPathCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands"{
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsInformationFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromWindowNameByTreeWalkerCommands"{
+v_TargetUIElementIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsInformationFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
+v_SelectionMethod : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_WindowSelectionMethod : String <<get>> <<set>> 
}
}

taskt.Core.Automation.Commands.UIAutomationGroup.IGetUIElementsXMLTreeFromSomethingProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementWindowResultsFromUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchSomewayProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementWindowResultsFromUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IDoSomethingUIElementProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementWindowResultsFromUIElementProperties
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsTreeXMLFromWindowHandleCommand ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IGetUIElementsXMLTreeFromSomethingProperties
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsTreeXMLFromWindowNameCommand ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IGetUIElementsXMLTreeFromSomethingProperties
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsTreeXMLFromUIElementCommand ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IGetUIElementsXMLTreeFromSomethingProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IGetUIElementsXMLTreeFromSomethingProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchSomewayProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchXPathProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchSomewayProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchParametersProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchSomewayProperties
taskt.Core.Automation.Commands.UIAutomationSearchChildrenUIElementsTreeXMLFromUIElementCommand ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchSomewayProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IDoSomethingUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByXPathCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IDoSomethingUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IDoSomethingUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.ADoSomethingUIElementCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IDoSomethingUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IGetFromUIElementProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IDoSomethingUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementActionProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IDoSomethingUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementSelectionItemsProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IDoSomethingUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromSomethingByXPathCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchXPathProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByXPathCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchXPathProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchXPathProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchXPathProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchParametersProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchParametersProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchParametersProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchParametersProperties
taskt.Core.Automation.Commands.UIAutomationSearchChildrenUIElementsInformationCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchChildUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchChildUIElementFromUIElementByXPathCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByXPathCommands
taskt.Core.Automation.Commands.UIAutomationWaitForUIElementToExistsCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationCheckUIElementExistsCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADoSomethingUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADoSomethingUIElementCommands
taskt.Core.Automation.Commands.UIAutomationSearchChildrenUIElementsTreeXMLFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADoSomethingUIElementCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsTreeXMLFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADoSomethingUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IGetFromUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementActionProperties
taskt.Core.Automation.Commands.UIAutomationGetSelectionItemsValueFromUIElementCommand ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementSelectionItemsProperties
taskt.Core.Automation.Commands.UIAutomationSelectItemInUIElementCommand ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementSelectionItemsProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByXPathCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByXPathCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByXPathCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByXPathCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchXPathProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByXPathCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchXPathProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchParametersProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchAnyUIElementProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchParametersProperties
taskt.Core.Automation.Commands.UIAutomationGetTextsFromTableUIElementAsDataTableCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetWindowUIElementFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetTableInformationFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetScrollBarInformationFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetWindowHandleFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetWindowNameFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetPropertyValueFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetUIElementPositionCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetUIElementSizeCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetSelectedStateFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetUIElementFromTableUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetSelectionItemsValueFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetTextFromTableUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetTextFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationGetParentUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AGetFromUIElementCommands
taskt.Core.Automation.Commands.UIAutomationScrollPercentUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands
taskt.Core.Automation.Commands.UIAutomationSetSelectedStateToUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands
taskt.Core.Automation.Commands.UIAutomationClickUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands
taskt.Core.Automation.Commands.UIAutomationExpandCollapseItemsInUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands
taskt.Core.Automation.Commands.UIAutomationScrollUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands
taskt.Core.Automation.Commands.UIAutomationSelectItemInUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands
taskt.Core.Automation.Commands.UIAutomationSelectUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands
taskt.Core.Automation.Commands.UIAutomationSetTextToUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionCommands
taskt.Core.Automation.Commands.UIAutomationSearchChildUIElementFromUIElementByXPathCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByXPathCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromUIElementByXPathCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowHandleByXPathCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowNameByXPathCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowNameCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationSearchChildrenUIElementsInformationCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchChildUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.ADescendantsSearchUIElementsFromWindowNameByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsInformationFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowNameCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchAnyUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchAnyUIElementProperties
taskt.Core.Automation.Commands.UIAutomationCheckUIElementExistsByXPathCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromUIElementByXPathCommands
taskt.Core.Automation.Commands.UIAutomationWaitForUIElementToExistsByXPathCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromUIElementByXPathCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromUIElementByXPathCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromUIElementByXPathCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromWindowHandleByXPathCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowHandleByXPathCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromWindowNameByXPathCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowNameByXPathCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsInformationFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowNameByTreeWalkerCommands --|> taskt.Core.Automation.Commands.ADescendantsSearchUIElementsFromWindowNameByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsInformationFromWindowNameCommand --|> taskt.Core.Automation.Commands.ADescendantsSearchUIElementsFromWindowNameByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationWaitForUIElementToExistsCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationCheckUIElementExistsCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromWindowNameCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowNameByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowNameCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
@enduml