@startuml
package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementDescendantsSearchSomewayProperties" {
+{abstract} v_MaxDepth : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}


taskt.Core.Automation.Commands.IExpandableProperties <|-- taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchSomewayProperties
@enduml