@startuml
UIAutomationCheckUIElementExistsCommand --> ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands --> ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands
ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands --> IDoSomethingUIElementProperties
ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands --> ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands
ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands --> IUIElementDescendantsSearchAnyUIElementProperties
ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands --> AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands
ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands --> IUIElementDescendantsSearchParametersProperties
AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands --> ScriptCommand
AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands --> IUIElementChildrenSearchParametersProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml