@startuml
UIAutomationCheckUIElementExistsByXPathCommand --> ADescendantsSearchUIElementsFromUIElementByXPathCommands
UIAutomationCheckUIElementExistsByXPathCommand --> IResultProperties
ADescendantsSearchUIElementsFromUIElementByXPathCommands --> ADescendantsSearchUIElementsFromSomethingByXPathCommands
ADescendantsSearchUIElementsFromUIElementByXPathCommands --> IUIElementCoreProperties
ADescendantsSearchUIElementsFromSomethingByXPathCommands --> AChildrenSearchUIElementsFromSomethingByXPathCommands
ADescendantsSearchUIElementsFromSomethingByXPathCommands --> IUIElementDescendantsSearchXPathProperties
AChildrenSearchUIElementsFromSomethingByXPathCommands --> ScriptCommand
AChildrenSearchUIElementsFromSomethingByXPathCommands --> IUIElementChildrenSearchXPathProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml