@startuml
UIAutomationSearchChildrenUIElementsInformationCommand --> AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands
UIAutomationSearchChildrenUIElementsInformationCommand --> IGetUIElementsInformationProperties
AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands --> AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands
AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands --> IDoSomethingUIElementProperties
AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands --> ScriptCommand
AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands --> IUIElementChildrenSearchParametersProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml