@startuml
UIAutomationGetUIElementPositionCommand --> AGetFromUIElementCommands
UIAutomationGetUIElementPositionCommand --> IPositionProperties
AGetFromUIElementCommands --> ADoSomethingUIElementCommands
AGetFromUIElementCommands --> IGetFromUIElementProperties
ADoSomethingUIElementCommands --> AUIElementCoreCommands
ADoSomethingUIElementCommands --> IDoSomethingUIElementProperties
AUIElementCoreCommands --> ScriptCommand
AUIElementCoreCommands --> IUIElementCoreProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml