@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
class "TryCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IHaveErrorAdditionalCommands" {
}
}

taskt.Core.Automation.Commands.TryCommand ..|> taskt.Core.Automation.Commands.IHaveErrorAdditionalCommands
@enduml