@startuml
AJSONValueActionCommands --> AJSONInputJSONCommands
AJSONValueActionCommands --> IJSONValueActionProperties
AJSONInputJSONCommands --> ScriptCommand
AJSONInputJSONCommands --> IJSONInputJSONProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml