@startuml
package "taskt.Core.Automation.Commands"{
abstract class "AJSONInsertValueToJContainerCommands"{
+v_Value : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AJSONAddInsertSetJContainerCommands"{
+v_Value : String <<get>> <<set>> 
+v_ValueType : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AJSONSetValueOfJContainerCommands"{
+v_Value : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "AddJSONArrayItemCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "AddJSONObjectPropertyCommand" <<sealed>> {
+RunCommand() : void 
+v_PropertyName : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SetJSONValueCommand" <<sealed>> {
+RunCommand() : void 
+v_JsonExtractor : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "InsertJSONArrayItemCommand" <<sealed>> {
+RunCommand() : void 
+v_Index : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "InsertJSONObjectPropertyCommand" <<sealed>> {
+RunCommand() : void 
+v_PropertyNameInsertPosition : String <<get>> <<set>> 
+v_PropertyName : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SetJSONValueOfJSONArrayCommand" <<sealed>> {
+RunCommand() : void 
+v_ArrayIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SetJSONValueOfJSONObjectCommand" <<sealed>> {
+RunCommand() : void 
+v_PropertyName : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Commands.AJSONAddInsertSetJContainerCommands <|-- taskt.Core.Automation.Commands.AJSONInsertValueToJContainerCommands
taskt.Core.Automation.Commands.AJSONAddInsertSetJContainerCommands <|-- taskt.Core.Automation.Commands.AJSONSetValueOfJContainerCommands
taskt.Core.Automation.Commands.AJSONAddInsertSetJContainerCommands <|-- taskt.Core.Automation.Commands.AddJSONArrayItemCommand
taskt.Core.Automation.Commands.AJSONAddInsertSetJContainerCommands <|-- taskt.Core.Automation.Commands.AddJSONObjectPropertyCommand
taskt.Core.Automation.Commands.AJSONAddInsertSetJContainerCommands <|-- taskt.Core.Automation.Commands.SetJSONValueCommand
taskt.Core.Automation.Commands.AJSONInsertValueToJContainerCommands <|-- taskt.Core.Automation.Commands.InsertJSONArrayItemCommand
taskt.Core.Automation.Commands.AJSONInsertValueToJContainerCommands <|-- taskt.Core.Automation.Commands.InsertJSONObjectPropertyCommand
taskt.Core.Automation.Commands.AJSONSetValueOfJContainerCommands <|-- taskt.Core.Automation.Commands.SetJSONValueOfJSONArrayCommand
taskt.Core.Automation.Commands.AJSONSetValueOfJContainerCommands <|-- taskt.Core.Automation.Commands.SetJSONValueOfJSONObjectCommand
@enduml