@startuml
ConvertJSONToListCommand --> AJSONGetFromJContainerCommands
ConvertJSONToListCommand --> IListResultProperties
AJSONGetFromJContainerCommands --> AJSONGetFromJSONCommands
AJSONGetFromJContainerCommands --> IJSONInputJContainer
AJSONGetFromJContainerCommands --> IJSONJSONPathProperties
AJSONGetFromJSONCommands --> AJSONInputJSONCommands
AJSONGetFromJSONCommands --> IResultProperties
AJSONInputJSONCommands --> ScriptCommand
AJSONInputJSONCommands --> IJSONInputJSONProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml