@startuml
GetJSONValuesAsDataTableCommand --> AJSONGetFromJContainerCommands
GetJSONValuesAsDataTableCommand --> IDataTableResultProperties
AJSONGetFromJContainerCommands --> AJSONGetFromJSONCommands
AJSONGetFromJContainerCommands --> IJSONInputJContainer
AJSONGetFromJContainerCommands --> IJSONJSONPathProperties
AJSONGetFromJSONCommands --> AJSONInputJSONCommands
AJSONGetFromJSONCommands --> IResultProperties
AJSONInputJSONCommands --> ScriptCommand
AJSONInputJSONCommands --> IJSONInputJSONProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml