@startuml
package "taskt.Core.Automation.Commands"{
Interface "IJSONValueProperties" {
+{abstract} v_Value : String <<get>> <<set>> <<abstract>> 
+{abstract} v_ValueType : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}


taskt.Core.Automation.Commands.IExpandableProperties <|-- taskt.Core.Automation.Commands.IJSONValueProperties
@enduml