@startuml
frmGUIInspectTool --> DialogLikeThemedForm
frmGUIInspectTool --> DialogLikeThemedForm
DialogLikeThemedForm --> ThemedForm
DialogLikeThemedForm --> ThemedForm
ThemedForm --> Form
ThemedForm --> Form
@enduml