@startuml
frmItemSelector --> DialogLikeThemedForm
frmItemSelector --> DialogLikeThemedForm
DialogLikeThemedForm --> ThemedForm
DialogLikeThemedForm --> ThemedForm
ThemedForm --> Form
ThemedForm --> Form
@enduml