@startuml
package "taskt.Core.Automation.Commands"{
Interface "IWaitDialogResultProperties" {
+{abstract} v_WhenCancel : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IDialogResultProperties" {
+{abstract} v_DialogResult : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}


taskt.Core.Automation.Commands.IDialogResultProperties <|-- taskt.Core.Automation.Commands.IWaitDialogResultProperties
taskt.Core.Automation.Commands.IExpandableProperties <|-- taskt.Core.Automation.Commands.IDialogResultProperties
@enduml