@startuml
ShowUserInputDialogCommand --> ScriptCommand
ShowUserInputDialogCommand --> IWaitDialogResultProperties
ShowUserInputDialogCommand --> IHaveDataTableElements
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml