@startuml
GetOneWindowPositionCommand --> AOneWindowNameCommands
GetOneWindowPositionCommand --> IWindowPositionProperties
AOneWindowNameCommands --> AWindowNameCoreCommands
AOneWindowNameCommands --> IOneWindowNameProperties
AWindowNameCoreCommands --> ScriptCommand
AWindowNameCoreCommands --> IWindowNameCoreProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml