@startuml
GetWindowStateFromWindowHandleCommand --> AWindowHandleCommands
GetWindowStateFromWindowHandleCommand --> IWindowStateProperties
AWindowHandleCommands --> ScriptCommand
AWindowHandleCommands --> IWindowHandleProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml