@startuml
GetWindowSizeFromWindowHandleCommand --> AWindowHandleCommands
GetWindowSizeFromWindowHandleCommand --> IWindowSizeProperties
AWindowHandleCommands --> ScriptCommand
AWindowHandleCommands --> IWindowHandleProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml