@startuml
package "taskt.Core.Automation.Commands"{
Interface "IWindowWaitTimeBetweenFindAndActionProperties" {
+{abstract} v_WaitTimeBetweenFindAndAction : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}


taskt.Core.Automation.Commands.IExpandableProperties <|-- taskt.Core.Automation.Commands.IWindowWaitTimeBetweenFindAndActionProperties
@enduml