@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
Interface "IWindowStateProperties" {
+{abstract} v_WindowState : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}

taskt.Core.Automation.Commands.IWindowStateProperties --|> taskt.Core.Automation.Commands.IExpandableProperties
@enduml