@startuml
MoveOneWindowCommand --> AOneWindowNameActionCommands
MoveOneWindowCommand --> IWindowPositionProperties
AOneWindowNameActionCommands --> AOneWindowNameCommands
AOneWindowNameActionCommands --> IOneWindowNameActionProperties
AOneWindowNameCommands --> AWindowNameCoreCommands
AOneWindowNameCommands --> IOneWindowNameProperties
AWindowNameCoreCommands --> ScriptCommand
AWindowNameCoreCommands --> IWindowNameCoreProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml