@startuml
SetOneWindowStateCommand --> AOneWindowNameActionCommands
SetOneWindowStateCommand --> IWindowStateProperties
AOneWindowNameActionCommands --> AOneWindowNameCommands
AOneWindowNameActionCommands --> IOneWindowNameActionProperties
AOneWindowNameCommands --> AWindowNameCoreCommands
AOneWindowNameCommands --> IOneWindowNameProperties
AWindowNameCoreCommands --> ScriptCommand
AWindowNameCoreCommands --> IWindowNameCoreProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml