@startuml
ARunCSharpSomethingCommands --> ACompileCSharpSomethingCommands
ACompileCSharpSomethingCommands --> ScriptCommand
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml