@startuml
CompileCSharpFileCommand --> ACompileCSharpSomethingCommands
CompileCSharpFileCommand --> ICanHandleFileName
CompileCSharpFileCommand --> ICanHandleFilePath
ACompileCSharpSomethingCommands --> ScriptCommand
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml