@startuml
CompileCSharpCodeCommand --> ACompileCSharpSomethingCommands
CompileCSharpCodeCommand --> ICanHandleFileName
ACompileCSharpSomethingCommands --> ScriptCommand
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml