@startuml
LoadScriptFileCommand --> AScriptFileCommands
AScriptFileCommands --> ScriptCommand
AScriptFileCommands --> IFileExistsFilePathProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml