@startuml
RunPowerShellScriptByCodeCommand --> ARunScriptByCodeCommands
ARunScriptByCodeCommands --> ScriptCommand
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml