@startuml
CreateColorFromExcelColorCommand --> AColorCreateCommands
AColorCreateCommands --> ScriptCommand
AColorCreateCommands --> IColorCreateProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml