@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
Interface "ICanHandleColor" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}

taskt.Core.Automation.Commands.ICanHandleColor --|> taskt.Core.Automation.Commands.IExpandableProperties
@enduml