@startuml
left to right direction
package "taskt.Core.Automation.Engine"{
class "ReportProgressEventArgs" {
+ProgressUpdate : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Engine.ReportProgressEventArgs -- EventArgs
@enduml