@startuml
left to right direction
package "taskt.Core.Automation.Engine"{
class "ScriptFinishedEventArgs" {
+LoggedOn : DateTime <<get>> <<set>> 
+Result : ScriptFinishedResult <<get>> <<set>> 
+Error : String <<get>> <<set>> 
+ExecutionTime : TimeSpan <<get>> <<set>> 
+FileName : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Engine.ScriptFinishedEventArgs -- EventArgs
@enduml