@startuml
package "taskt.Core.Automation.Commands"{
abstract class "AFileExistsFilePathCommands"{
+v_WaitTimeForFile : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFileFilePathCommands"{
+v_TargetFilePath : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExtractionFilePathCommand" <<sealed>> {
+RunCommand() : void 
-lnkFormatChecker_Click() : void 
+v_Format : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFileExistsFilePathBeforeAfterResultCommands"{
+v_BeforeFilePathResult : String <<get>> <<set>> 
+v_AfterFilePathResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFileExistsFilePathPathResultCommands"{
+v_ResultPath : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFileCopyMoveFileCommands"{
#CreateActionFunc() : Func
+v_DestinationFolderPath : String <<get>> <<set>> 
+v_CreateDirectory : String <<get>> <<set>> 
+v_WhenDestinationIsSame : String <<get>> <<set>> 
+v_WhenDestinationExists : String <<get>> <<set>> 
+v_WaitTimeForFolder : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFileCopySameRenameFileCommands"{
#CreateActionFunc() : Func
#cmbExtensionOption_SelectionChange() : void 
+v_NewFileName : String <<get>> <<set>> 
+v_ExtensionOption : String <<get>> <<set>> 
+v_NewExtension : String <<get>> <<set>> 
+v_WhenFileNameSame : String <<get>> <<set>> 
+v_WhenNewFileExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "OpenFileCommand" <<sealed>> {
+RunCommand() : void 
+v_WaitTimeForOpen : String <<get>> <<set>> 
+v_WindowNameResult : String <<get>> <<set>> 
+v_WindowHandleResult : String <<get>> <<set>> 
+v_WaitTimeForFile : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetFileInformationCommand" <<sealed>> {
+RunCommand() : void 
+AddInstance() : void 
+RemoveInstance() : void 
+v_InfoType : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CheckFileExistsCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForFile : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "DeleteFileCommand" <<sealed>> {
+RunCommand() : void 
+v_WhenFileDoesNotExists : String <<get>> <<set>> 
+v_MoveToRecycleBin : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "WaitForFileToExistCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "CopyFileCommand" <<sealed>> {
+RunCommand() : void 
+v_DestinationFolderPath : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "MoveFileCommand" <<sealed>> {
+RunCommand() : void 
+v_DestinationFolderPath : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CopyFileToSameFolderCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "RenameFileCommand" <<sealed>> {
+RunCommand() : void 
}
}


taskt.Core.Automation.Commands.AFileFilePathCommands <|-- taskt.Core.Automation.Commands.AFileExistsFilePathCommands
taskt.Core.Automation.Commands.AFileFilePathCommands <|-- taskt.Core.Automation.Commands.ExtractionFilePathCommand
taskt.Core.Automation.Commands.AFileExistsFilePathCommands <|-- taskt.Core.Automation.Commands.AFileExistsFilePathBeforeAfterResultCommands
taskt.Core.Automation.Commands.AFileExistsFilePathCommands <|-- taskt.Core.Automation.Commands.AFileExistsFilePathPathResultCommands
taskt.Core.Automation.Commands.AFileExistsFilePathBeforeAfterResultCommands <|-- taskt.Core.Automation.Commands.AFileCopyMoveFileCommands
taskt.Core.Automation.Commands.AFileExistsFilePathBeforeAfterResultCommands <|-- taskt.Core.Automation.Commands.AFileCopySameRenameFileCommands
taskt.Core.Automation.Commands.AFileExistsFilePathPathResultCommands <|-- taskt.Core.Automation.Commands.OpenFileCommand
taskt.Core.Automation.Commands.AFileExistsFilePathPathResultCommands <|-- taskt.Core.Automation.Commands.GetFileInformationCommand
taskt.Core.Automation.Commands.AFileExistsFilePathPathResultCommands <|-- taskt.Core.Automation.Commands.CheckFileExistsCommand
taskt.Core.Automation.Commands.AFileExistsFilePathPathResultCommands <|-- taskt.Core.Automation.Commands.DeleteFileCommand
taskt.Core.Automation.Commands.AFileExistsFilePathPathResultCommands <|-- taskt.Core.Automation.Commands.WaitForFileToExistCommand
taskt.Core.Automation.Commands.AFileCopyMoveFileCommands <|-- taskt.Core.Automation.Commands.CopyFileCommand
taskt.Core.Automation.Commands.AFileCopyMoveFileCommands <|-- taskt.Core.Automation.Commands.MoveFileCommand
taskt.Core.Automation.Commands.AFileCopySameRenameFileCommands <|-- taskt.Core.Automation.Commands.CopyFileToSameFolderCommand
taskt.Core.Automation.Commands.AFileCopySameRenameFileCommands <|-- taskt.Core.Automation.Commands.RenameFileCommand
@enduml