@startuml
AFileExistsFilePathCommands --> AFileFilePathCommands
AFileExistsFilePathCommands --> IFileExistsFilePathProperties
AFileFilePathCommands --> ScriptCommand
AFileFilePathCommands --> IFilePathProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml