@startuml
ExtractZipFileCommand --> ScriptCommand
ExtractZipFileCommand --> ICanHandleList
ExtractZipFileCommand --> ICanHandleFilePath
ExtractZipFileCommand --> ICanHandleFolderPath
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml