@startuml
RenameFileCommand --> AFileCopySameRenameFileCommands
AFileCopySameRenameFileCommands --> AFileExistsFilePathBeforeAfterResultCommands
AFileCopySameRenameFileCommands --> ICanHandleFileName
AFileExistsFilePathBeforeAfterResultCommands --> AFileExistsFilePathCommands
AFileExistsFilePathBeforeAfterResultCommands --> IFileExistsFilePathBeforeAfterPathResultProperties
AFileExistsFilePathCommands --> AFileFilePathCommands
AFileExistsFilePathCommands --> IFileExistsFilePathProperties
AFileFilePathCommands --> ScriptCommand
AFileFilePathCommands --> IFilePathProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml