@startuml
package "taskt.Core.Automation.Commands"{
abstract class "ADictionaryAddCreateCommands"{
+BeforeValidate() : void 
+AddDataAndValueFromDataTable() : void 
+v_ColumnNameDataTable : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "ADictionaryInputDictionaryCommands"{
+v_Dictionary : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "ADictionaryGetFromDictionaryCommands"{
+{abstract} v_Result : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "ADictionaryKeyCommands"{
+v_Key : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExportDictionaryAsTextFileCommand" <<sealed>> {
+RunCommand() : void 
+v_FilePath : String <<get>> <<set>> 
+v_ExportHeader : String <<get>> <<set>> 
+v_ExportIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "BeginLoopForDictionaryCommand" <<sealed>> {
+RunCommand() : void 
+v_Value : String <<get>> <<set>> 
+v_Key : String <<get>> <<set>> 
+v_ReverseLoop : String <<get>> <<set>> 
+v_CurrentTimes : String <<get>> <<set>> 
+v_NumberOfLoops : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ReplaceDictionaryCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbReplaceAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_Dictionary : String <<get>> <<set>> 
+v_ValueType : String <<get>> <<set>> 
+v_ReplaceAction : String <<get>> <<set>> 
+v_ReplaceActionParameterTable : DataTable <<get>> <<set>> 
+v_NewValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "AddDictionaryItemCommand" <<sealed>> {
+RunCommand() : void 
+v_Dictionary : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CreateDictionaryCommand" <<sealed>> {
+RunCommand() : void 
+v_Dictionary : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ConvertDictionaryToVisualizedTextCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ConvertDictionaryToTextCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_ExportHeader : String <<get>> <<set>> 
+v_ExportIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "JoinDictionaryValuesAsTextCommand" <<sealed>> {
+RunCommand() : void 
+v_Separator : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_BeforeText : String <<get>> <<set>> 
+v_AfterText : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ConvertDictionaryToDataTableCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ConvertDictionaryToListCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ConvertDictionaryToJSONCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetDictionaryKeysListCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetDictionaryKeyFromValueCommand" <<sealed>> {
+RunCommand() : void 
+v_Value : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "ADictionaryKeyActionCommands"{
+v_WhenKeyDoesNotExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CheckDictionaryKeyExistsCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "RemoveDictionaryItemCommand" <<sealed>> {
+RunCommand() : void 
+v_WhenKeyDoesNotExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SetDictionaryValueCommand" <<sealed>> {
+RunCommand() : void 
+v_Value : String <<get>> <<set>> 
+v_WhenKeyDoesNotExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetDictionaryValueCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WhenKeyDoesNotExists : String <<get>> <<set>> 
+v_KeyType : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Commands.ADictionaryInputDictionaryCommands <|-- taskt.Core.Automation.Commands.ADictionaryAddCreateCommands
taskt.Core.Automation.Commands.ADictionaryInputDictionaryCommands <|-- taskt.Core.Automation.Commands.ADictionaryGetFromDictionaryCommands
taskt.Core.Automation.Commands.ADictionaryInputDictionaryCommands <|-- taskt.Core.Automation.Commands.ADictionaryKeyCommands
taskt.Core.Automation.Commands.ADictionaryInputDictionaryCommands <|-- taskt.Core.Automation.Commands.ExportDictionaryAsTextFileCommand
taskt.Core.Automation.Commands.ADictionaryInputDictionaryCommands <|-- taskt.Core.Automation.Commands.BeginLoopForDictionaryCommand
taskt.Core.Automation.Commands.ADictionaryInputDictionaryCommands <|-- taskt.Core.Automation.Commands.ReplaceDictionaryCommand
taskt.Core.Automation.Commands.ADictionaryAddCreateCommands <|-- taskt.Core.Automation.Commands.AddDictionaryItemCommand
taskt.Core.Automation.Commands.ADictionaryAddCreateCommands <|-- taskt.Core.Automation.Commands.CreateDictionaryCommand
taskt.Core.Automation.Commands.ADictionaryGetFromDictionaryCommands <|-- taskt.Core.Automation.Commands.ConvertDictionaryToVisualizedTextCommand
taskt.Core.Automation.Commands.ADictionaryGetFromDictionaryCommands <|-- taskt.Core.Automation.Commands.ConvertDictionaryToTextCommand
taskt.Core.Automation.Commands.ADictionaryGetFromDictionaryCommands <|-- taskt.Core.Automation.Commands.JoinDictionaryValuesAsTextCommand
taskt.Core.Automation.Commands.ADictionaryGetFromDictionaryCommands <|-- taskt.Core.Automation.Commands.ConvertDictionaryToDataTableCommand
taskt.Core.Automation.Commands.ADictionaryGetFromDictionaryCommands <|-- taskt.Core.Automation.Commands.ConvertDictionaryToListCommand
taskt.Core.Automation.Commands.ADictionaryGetFromDictionaryCommands <|-- taskt.Core.Automation.Commands.ConvertDictionaryToJSONCommand
taskt.Core.Automation.Commands.ADictionaryGetFromDictionaryCommands <|-- taskt.Core.Automation.Commands.GetDictionaryKeysListCommand
taskt.Core.Automation.Commands.ADictionaryGetFromDictionaryCommands <|-- taskt.Core.Automation.Commands.GetDictionaryKeyFromValueCommand
taskt.Core.Automation.Commands.ADictionaryKeyCommands <|-- taskt.Core.Automation.Commands.ADictionaryKeyActionCommands
taskt.Core.Automation.Commands.ADictionaryKeyCommands <|-- taskt.Core.Automation.Commands.CheckDictionaryKeyExistsCommand
taskt.Core.Automation.Commands.ADictionaryKeyActionCommands <|-- taskt.Core.Automation.Commands.RemoveDictionaryItemCommand
taskt.Core.Automation.Commands.ADictionaryKeyActionCommands <|-- taskt.Core.Automation.Commands.SetDictionaryValueCommand
taskt.Core.Automation.Commands.ADictionaryKeyActionCommands <|-- taskt.Core.Automation.Commands.GetDictionaryValueCommand
@enduml