@startuml
ADictionaryCreateFromDictionaryCommands --> ScriptCommand
ADictionaryCreateFromDictionaryCommands --> IDictionaryCreateFromDictionary
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml