@startuml
ConvertDictionaryToListCommand --> ADictionaryGetFromDictionaryCommands
ConvertDictionaryToListCommand --> IListResultProperties
ADictionaryGetFromDictionaryCommands --> ADictionaryInputDictionaryCommands
ADictionaryGetFromDictionaryCommands --> IDictionaryGetFromDictionaryProperties
ADictionaryInputDictionaryCommands --> ScriptCommand
ADictionaryInputDictionaryCommands --> IDictionaryProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml