@startuml
MailKitGetAddressesAsListCommand --> ScriptCommand
MailKitGetAddressesAsListCommand --> ICanHandleList
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml