@startuml
MailKitGetAddressesAsDataTableCommand --> ScriptCommand
MailKitGetAddressesAsDataTableCommand --> ICanHandleDataTable
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml