@startuml
MailKitGetEMailAttachmentsNameCommand --> ScriptCommand
MailKitGetEMailAttachmentsNameCommand --> ICanHandleList
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml