@startuml
DatabaseExecuteQueryCommand --> ScriptCommand
DatabaseExecuteQueryCommand --> ICanHandleDataTable
DatabaseExecuteQueryCommand --> IHaveDataTableElements
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml