@startuml
package "taskt.Core.Automation.Commands"{
Interface "ICanHandleFileOrFolderName" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}


taskt.Core.Automation.Commands.IExpandableProperties <|-- taskt.Core.Automation.Commands.ICanHandleFileOrFolderName
@enduml