@startuml
package "taskt.Core.Automation.Commands"{
Interface "ICanHandleFileName" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "ICanHandleFileOrFolderName" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "ICanHandleFolderName" {
}
}

package "taskt.Core.Automation.Commands"{
class "CompileCSharpFileCommand" <<sealed>> {
+RunCommand() : void 
+v_TargetFilePath : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CompileCSharpCodeCommand" <<sealed>> {
+RunCommand() : void 
-lnkShowCodeBuilderLink_Clicked() : void 
+v_Code : String <<get>> <<set>> 
+v_ReplaceScriptVariables : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFileCopySameRenameFileCommands"{
#CreateActionFunc() : Func
#cmbExtensionOption_SelectionChange() : void 
+v_NewFileName : String <<get>> <<set>> 
+v_ExtensionOption : String <<get>> <<set>> 
+v_NewExtension : String <<get>> <<set>> 
+v_WhenFileNameSame : String <<get>> <<set>> 
+v_WhenNewFileExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetRandomFilePathCommand" {
+RunCommand() : void 
+v_TargetFolderPath : String <<get>> <<set>> 
+v_Extension : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_CheckFileDoesNotExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFileNumberedFileCommands"{
#SearchNonExistentFileAction() : void 
+v_TargetFolderPath : String <<get>> <<set>> 
+v_BeforeFileCounter : String <<get>> <<set>> 
+v_Digits : String <<get>> <<set>> 
+v_AfterFileCounter : String <<get>> <<set>> 
+v_Extension : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_StartValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "LogDataCommand" <<sealed>> {
+RunCommand() : void 
+v_LogFile : String <<get>> <<set>> 
+v_LogText : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "AFolderCopySameRenameFolderCommands"{
#CreateActionFunc() : Func
+v_NewFolderName : String <<get>> <<set>> 
+v_WhenFolderNameSame : String <<get>> <<set>> 
+v_WhenDestinationExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CreateFolderCommand" <<sealed>> {
+RunCommand() : void 
+v_NewFolderName : String <<get>> <<set>> 
+v_WhenFolderExists : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CopyFileToSameFolderCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "RenameFileCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "GetLastExistentNumberedFilePathCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "GetNonExistentFilePathCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "CopyFolderInSamLocationCommand" <<sealed>> {
+RunCommand() : void 
+v_CopySubFolder : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "RenameFolderCommand" <<sealed>> {
+RunCommand() : void 
}
}


taskt.Core.Automation.Commands.ICanHandleFileOrFolderName <|-- taskt.Core.Automation.Commands.ICanHandleFileName
taskt.Core.Automation.Commands.ICanHandleFileOrFolderName <|-- taskt.Core.Automation.Commands.ICanHandleFolderName
taskt.Core.Automation.Commands.ICanHandleFileName <|.. taskt.Core.Automation.Commands.CompileCSharpFileCommand
taskt.Core.Automation.Commands.ICanHandleFileName <|.. taskt.Core.Automation.Commands.CompileCSharpCodeCommand
taskt.Core.Automation.Commands.ICanHandleFileName <|.. taskt.Core.Automation.Commands.AFileCopySameRenameFileCommands
taskt.Core.Automation.Commands.ICanHandleFileName <|.. taskt.Core.Automation.Commands.GetRandomFilePathCommand
taskt.Core.Automation.Commands.ICanHandleFileName <|.. taskt.Core.Automation.Commands.AFileNumberedFileCommands
taskt.Core.Automation.Commands.ICanHandleFileName <|.. taskt.Core.Automation.Commands.LogDataCommand
taskt.Core.Automation.Commands.ICanHandleFolderName <|.. taskt.Core.Automation.Commands.AFolderCopySameRenameFolderCommands
taskt.Core.Automation.Commands.ICanHandleFolderName <|.. taskt.Core.Automation.Commands.CreateFolderCommand
taskt.Core.Automation.Commands.AFileCopySameRenameFileCommands <|-- taskt.Core.Automation.Commands.CopyFileToSameFolderCommand
taskt.Core.Automation.Commands.AFileCopySameRenameFileCommands <|-- taskt.Core.Automation.Commands.RenameFileCommand
taskt.Core.Automation.Commands.AFileNumberedFileCommands <|-- taskt.Core.Automation.Commands.GetLastExistentNumberedFilePathCommand
taskt.Core.Automation.Commands.AFileNumberedFileCommands <|-- taskt.Core.Automation.Commands.GetNonExistentFilePathCommand
taskt.Core.Automation.Commands.AFolderCopySameRenameFolderCommands <|-- taskt.Core.Automation.Commands.CopyFolderInSamLocationCommand
taskt.Core.Automation.Commands.AFolderCopySameRenameFolderCommands <|-- taskt.Core.Automation.Commands.RenameFolderCommand
@enduml