@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
class "EndTryCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IEndOfStacturedCommand" {
}
}

package "taskt.Core.Automation.Commands"{
class "EndLoopCommand" <<sealed>> {
+Render() : List
+GetDisplayValue() : String
}
}

package "taskt.Core.Automation.Commands"{
class "EndIfCommand" <<sealed>> {
+Render() : List
+GetDisplayValue() : String
}
}

taskt.Core.Automation.Commands.EndTryCommand ..|> taskt.Core.Automation.Commands.IEndOfStacturedCommand
taskt.Core.Automation.Commands.EndLoopCommand ..|> taskt.Core.Automation.Commands.IEndOfStacturedCommand
taskt.Core.Automation.Commands.EndIfCommand ..|> taskt.Core.Automation.Commands.IEndOfStacturedCommand
@enduml