@startuml
left to right direction
package "taskt.Core.Automation.Commands.KeyMouseGroup"{
Interface "ISendAdvancedKeyStrokesProperties" {
+{abstract} v_KeyActions : DataTable <<get>> <<set>> <<abstract>> 
+{abstract} v_KeyUpDefault : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IHaveDataTableElements" {
+{abstract} BeforeValidate() : void <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementChildrenSearchParametersProperties" {
+{abstract} v_SearchParameters : DataTable <<get>> <<set>> <<abstract>> 
+{abstract} v_MaxNumberUIElements : String <<get>> <<set>> <<abstract>> 
+{abstract} v_SiblingsDirection : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementUIElementActionSomewayProperties" {
+{abstract} v_AutomationType : String <<get>> <<set>> <<abstract>> 
+{abstract} v_UIAActionParameters : DataTable <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumGetOneWebElementValuesAsSomethingCommands"{
+BeforeValidate() : void 
#GetOneWebElementMultiValuesAction() : void 
+v_AttributesName : DataTable <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserWebElementActionAfterSearchWebElementFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+AfterShown() : void 
-cmbSearchType_SelectionChangeCommited() : void 
-cmbSeleniumAction_SelectionChangeCommitted() : void 
-{static} AddDataTableRows() : void 
-{static} AddDataTableRows() : void 
-{static} ActionParameterProcess() : void 
-{static} CreateComboBox() : DataGridViewComboBoxCell
+GetDisplayValue() : String
+BeforeValidate() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_WebElementAction : String <<get>> <<set>> 
+v_WebActionParameterTable : DataTable <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
+v_ScrollToWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ReplaceDataTableValueCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbReplaceAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_ValueType : String <<get>> <<set>> 
+v_ReplaceAction : String <<get>> <<set>> 
+v_ReplaceActionParameterTable : DataTable <<get>> <<set>> 
+v_NewValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ReplaceDataTableRowValueCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbReplaceAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_ValueType : String <<get>> <<set>> 
+v_ReplaceAction : String <<get>> <<set>> 
+v_ReplaceActionParameterTable : DataTable <<get>> <<set>> 
+v_NewValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FilterDataTableColumnByRowValueCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbFilterAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_TargetDataTable : String <<get>> <<set>> 
+v_RowIndex : String <<get>> <<set>> 
+v_ValueType : String <<get>> <<set>> 
+v_FilterAction : String <<get>> <<set>> 
+v_FilterActionParameterTable : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ReplaceDataTableColumnValueCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbReplaceAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_ValueType : String <<get>> <<set>> 
+v_ReplaceAction : String <<get>> <<set>> 
+v_ReplaceActionParameterTable : DataTable <<get>> <<set>> 
+v_NewValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FilterDataTableRowByColumnValueCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbFilterAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_TargetDataTable : String <<get>> <<set>> 
+v_ColumnType : String <<get>> <<set>> 
+v_ColumnIndex : String <<get>> <<set>> 
+v_ValueType : String <<get>> <<set>> 
+v_FilterAction : String <<get>> <<set>> 
+v_FilterActionParameterTable : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "AddDataTableRowCommand" <<sealed>> {
+RunCommand() : void 
+BeforeValidate() : void 
+v_AddDataDataTable : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FilterDictionaryCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbFilterAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_TargetDictionary : String <<get>> <<set>> 
+v_ValueType : String <<get>> <<set>> 
+v_FilterAction : String <<get>> <<set>> 
+v_FilterActionParameterTable : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ReplaceDictionaryCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbReplaceAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_Dictionary : String <<get>> <<set>> 
+v_ValueType : String <<get>> <<set>> 
+v_ReplaceAction : String <<get>> <<set>> 
+v_ReplaceActionParameterTable : DataTable <<get>> <<set>> 
+v_NewValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ReplaceListCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbReplaceAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_List : String <<get>> <<set>> 
+v_ValueType : String <<get>> <<set>> 
+v_ReplaceAction : String <<get>> <<set>> 
+v_ReplaceActionParameterTable : DataTable <<get>> <<set>> 
+v_NewValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "FilterListCommand" <<sealed>> {
+RunCommand() : void 
-cmbTargetType_SelectionChangeCommited() : void 
-cmbFilterAction_SelectionChangeCommited() : void 
+AfterShown() : void 
+BeforeValidate() : void 
+v_TargetList : String <<get>> <<set>> 
+v_ValueType : String <<get>> <<set>> 
+v_FilterAction : String <<get>> <<set>> 
+v_FilterActionParameterTable : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExtractionTextCommand" <<sealed>> {
+RunCommand() : void 
-cmbTextExtraction_SelectionChangeCommitted() : void 
-{static} ExtractLeadingText() : String
-{static} ExtractTrailingText() : String
-{static} SearchTextPositions() : List
+BeforeValidate() : void 
+v_InputValue : String <<get>> <<set>> 
+v_TextExtractionType : String <<get>> <<set>> 
+v_TextExtractionTable : DataTable <<get>> <<set>> 
+v_applyToVariableName : String <<get>> <<set>> 
+v_WhenTextNotFound : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "CreateListCommand" <<sealed>> {
+RunCommand() : void 
+BeforeValidate() : void 
+v_List : String <<get>> <<set>> 
+v_ListValues : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetWebElementsValuesAsDataTableCommand" <<sealed>> {
+RunCommand() : void 
+BeforeValidate() : void 
+v_AttributesName : DataTable <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "AddDictionaryItemCommand" <<sealed>> {
+RunCommand() : void 
+v_Dictionary : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "BeginLoopCommand" <<sealed>> {
-LoopGridViewHelper_MouseEnter() : void 
+RunCommand() : void 
+Render() : List
-loopAction_SelectionChangeCommitted() : void 
-linkWebBrowserInstanceSelector_Click() : void 
-linkWindowNameSelector_Click() : void 
-linkBooleanInstanceSelector_Click() : void 
+GetDisplayValue() : String
+IsValidate() : Boolean
+ConvertToIntermediate() : void 
+ConvertToRaw() : void 
+BeforeValidate() : void 
+v_LoopActionType : String <<get>> <<set>> 
+v_LoopActionParameterTable : DataTable <<get>> <<set>> 
-LoopGridViewHelper : System.Windows.Forms.DataGridView
-ActionDropdown : System.Windows.Forms.ComboBox
-ParameterControls : List<System.Windows.Forms.Control>
-lnkBrowserInstanceSelector : taskt.UI.CustomControls.CommandItemControl
-lnkWindowNameSelector : taskt.UI.CustomControls.CommandItemControl
-lnkBooleanSelector : taskt.UI.CustomControls.CommandItemControl
}
}

package "taskt.Core.Automation.Commands"{
class "BeginMultiLoopCommand" <<sealed>> {
+RunCommand() : void 
-DetermineMultiStatementTruth() : Boolean
+Render() : List
-LoopConditionHelper_CellContentClick() : void 
-CreateLoopCondition() : void 
+GetDisplayValue() : String
+v_LoopConditionsTable : DataTable <<get>> <<set>> 
-ScriptVariables : List <<get>> <<private set>>
-LoopConditionHelper : System.Windows.Forms.DataGridView
-appSettings : taskt.Core.SafeApplicationSettings
}
}

package "taskt.Core.Automation.Commands"{
class "BeginMultiIfCommand" <<sealed>> {
+RunCommand() : void 
+Render() : List
-IfConditionHelper_CellContentClick() : void 
-CreateIfCondition() : void 
+GetDisplayValue() : String
+v_IfConditionsTable : DataTable <<get>> <<set>> 
-ScriptVariables : List <<get>> <<private set>>
-IfConditionHelper : System.Windows.Forms.DataGridView
-appSetting : taskt.Core.SafeApplicationSettings
}
}

package "taskt.Core.Automation.Commands"{
class "BeginIfCommand" <<sealed>> {
-IfGridViewHelper_MouseEnter() : void 
+RunCommand() : void 
+Render() : List
-linkWebBrowserInstanceSelector_Click() : void 
-linkWindowNameSelector_Click() : void 
-linkBooleanInstanceSelector_Click() : void 
-ifAction_SelectionChangeCommitted() : void 
+GetDisplayValue() : String
+IsValidate() : Boolean
+ConvertToIntermediate() : void 
+ConvertToRaw() : void 
+BeforeValidate() : void 
+v_IfActionType : String <<get>> <<set>> 
+v_IfActionParameterTable : DataTable <<get>> <<set>> 
-IfGridViewHelper : System.Windows.Forms.DataGridView
-ActionDropdown : System.Windows.Forms.ComboBox
-ParameterControls : List<System.Windows.Forms.Control>
-lnkBrowserInstanceSelector : taskt.UI.CustomControls.CommandItemControl
-lnkWindowNameSelector : taskt.UI.CustomControls.CommandItemControl
-lnkBooleanSelector : taskt.UI.CustomControls.CommandItemControl
}
}

package "taskt.Core.Automation.Commands"{
class "DatabaseExecuteQueryCommand" <<sealed>> {
+RunCommand() : void 
+Render() : List
-AddParameter() : void 
+GetDisplayValue() : String
+QueryParametersGridView_CellClick() : void 
+v_InstanceName : String <<get>> <<set>> 
+v_QueryType : String <<get>> <<set>> 
+v_Query : String <<get>> <<set>> 
+v_QueryParameters : DataTable <<get>> <<set>> 
+v_DatasetName : String <<get>> <<set>> 
-QueryParametersGridView : System.Windows.Forms.DataGridView
-QueryParametersControls : List<System.Windows.Forms.Control>
}
}

package "taskt.Core.Automation.Commands"{
class "HTTPExecuteRESTAPICommand" <<sealed>> {
+RunCommand() : void 
+ExecuteRESTRequest() : String
+BeforeValidate() : void 
+v_BaseURL : String <<get>> <<set>> 
+v_Port : String <<get>> <<set>> 
+v_APIEndPoint : String <<get>> <<set>> 
+v_APIMethodType : String <<get>> <<set>> 
+v_RESTParameters : DataTable <<get>> <<set>> 
+v_userVariableName : String <<get>> <<set>> 
+v_AdvancedParameters : DataTable <<get>> <<set>> 
+v_RequestFormat : String <<get>> <<set>> 
+v_Timeout : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserWebElementActionAfterSearchWebElementCommand" <<sealed>> {
+RunCommand() : void 
+AfterShown() : void 
-cmbSearchType_SelectionChangeCommited() : void 
-cmbSeleniumAction_SelectionChangeCommitted() : void 
-{static} AddDataTableRows() : void 
-{static} AddDataTableRows() : void 
-{static} ActionParameterProcess() : void 
-{static} CreateComboBox() : DataGridViewComboBoxCell
+GetDisplayValue() : String
+BeforeValidate() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_WebElementAction : String <<get>> <<set>> 
+v_WebActionParameterTable : DataTable <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
+v_ScrollToWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ShowUserInputDialogCommand" <<sealed>> {
+RunCommand() : void 
-lnkAddInputParameter_Click() : void 
-lnkUpInputParameter_Click() : void 
-lnkDownInputParameter_Click() : void 
-lnkDeleteInputParameter_Click() : void 
-SwapUserInputParameterRows() : void 
+IsValidate() : Boolean
+BeforeValidate() : void 
+v_DialogTitle : String <<get>> <<set>> 
+v_Message : String <<get>> <<set>> 
+v_UserInputConfig : DataTable <<get>> <<set>> 
+v_DialogButtons : String <<get>> <<set>> 
+v_WhenCancel : String <<get>> <<set>> 
+v_DialogResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "ExecuteDLLCommand" <<sealed>> {
+RunCommand() : void 
+BeforeValidate() : void 
-lnkGenerateDLLParameters_Clicked() : void 
-lnkShowDLLExplorer_Clicked() : void 
+v_FilePath : String <<get>> <<set>> 
+v_ClassName : String <<get>> <<set>> 
+v_MethodName : String <<get>> <<set>> 
+v_applyToVariableName : String <<get>> <<set>> 
+v_MethodParameters : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SendAdvancedKeyStrokesFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+AfterShown() : void 
+IsValidate() : Boolean
+BeforeValidate() : void 
+v_KeyActions : DataTable <<get>> <<set>> 
+v_KeyUpDefault : String <<get>> <<set>> 
+v_WaitTimeAfterKeyEnter : String <<get>> <<set>> 
+v_ActivateCurrentWindow : String <<get>> <<set>> 
+v_ActivateBeforeAction : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SendAdvancedKeyStrokesCommand" <<sealed>> {
+RunCommand() : void 
+AfterShown() : void 
+IsValidate() : Boolean
+BeforeValidate() : void 
+v_KeyActions : DataTable <<get>> <<set>> 
+v_KeyUpDefault : String <<get>> <<set>> 
+v_WaitTimeAfterKeyEnter : String <<get>> <<set>> 
+v_ActivateCurrentWindow : String <<get>> <<set>> 
+v_ActivateBeforeAction : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands"{
+AfterShown() : void 
+BeforeValidate() : void 
+v_SearchParameters : DataTable <<get>> <<set>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
+v_MaxNumberUIElements : String <<get>> <<set>> 
+v_SiblingsDirection : String <<get>> <<set>> 
+v_WindowNameResult : String <<get>> <<set>> 
+v_WindowHandleResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromSomethingByTreeWalkerCommands"{
+v_SearchParameters : DataTable <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
+v_AutomationType : String <<get>> <<set>> 
+v_UIAActionParameters : DataTable <<get>> <<set>> 
+v_MaxNumberUIElements : String <<get>> <<set>> 
+v_SiblingsDirection : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementDescendantsSearchParametersProperties" {
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionSomewayCommands"{
#UIElementActionProcess() : void 
+AfterShown() : void 
#cmbActionType_SelectedItemChange() : void 
#{static} AddDataTableRows() : void 
#{static} SetComboBoxParameterProcess() : void 
#{static} ApplyDGVCombBox() : void 
#{static} CreateDGVComboBox() : DataGridViewComboBoxCell
+BeforeValidate() : void 
+{abstract} v_AutomationType : String <<get>> <<set>> <<abstract>> 
+{abstract} v_UIAActionParameters : DataTable <<get>> <<set>> <<abstract>> 
+v_WaitTimeForUIElement : String <<get>> <<set>> 
+v_MaxSiblings : String <<get>> <<set>> 
+v_MaxDepth : String <<get>> <<set>> 
+v_TargetUIElement : String <<get>> <<set>> 
+v_WindowNameResult : String <<get>> <<set>> 
+v_WindowHandleResult : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetOneWebElementValuesAsDataTableCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetOneWebElementValuesAsListCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetOneWebElementValuesAsDictionaryCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands"{
+v_TargetElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands"{
+v_MaxDepth : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromWindowSomethingByTreeWalkerCommands"{
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
Interface "IUIElementDescendantsSearchAnyUIElementProperties" {
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromSomethingByXPathCommands"{
+v_AutomationType : String <<get>> <<set>> 
+v_SearchXPath : String <<get>> <<set>> 
+v_UIAActionParameters : DataTable <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchChildrenUIElementsInformationCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchChildUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands"{
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
+v_MaxNumberUIElements : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands"{
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "ADescendantsSearchUIElementsFromWindowNameByTreeWalkerCommands"{
#MatchMethodComboBox_SelectionChangeCommitted() : void 
+Refresh() : void 
#SearchWindowAfterAction() : void 
+v_WindowName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetWindowIndex : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_WindowUIElement : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsInformationFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_TargetElement : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
-MatchMethodComboBox_SelectionChangeCommitted() : void 
+Refresh() : void 
+v_WindowName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_WindowSelectionMethod : String <<get>> <<set>> 
+v_TargetWindowIndex : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "AUIElementActionFromWindowSomethingByXPathCommands"{
+v_WindowUIElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands"{
+v_TargetElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands"{
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetUIElementIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsInformationFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.UIAutomationGroup"{
abstract class "ADescendantsSearchAnyUIElementFromWindowNameByTreeWalkerCommands"{
+v_TargetUIElementIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementsInformationFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_WindowHandle : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
-MatchMethodComboBox_SelectionChangeCommitted() : void 
+Refresh() : void 
+v_WindowName : String <<get>> <<set>> 
+v_CheckMethod : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_TargetWindowIndex : String <<get>> <<set>> 
+v_WaitTimeForWindow : String <<get>> <<set>> 
+v_CaseSensitive : String <<get>> <<set>> 
+v_TrimBeforeCheck : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationWaitForUIElementToExistsCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationCheckUIElementExistsCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromUIElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromWindowHandleCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "UIAutomationSearchUIElementFromWindowNameCommand" <<sealed>> {
+RunCommand() : void 
+v_SelectionMethod : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_WindowSelectionMethod : String <<get>> <<set>> 
}
}

taskt.Core.Automation.Commands.KeyMouseGroup.ISendAdvancedKeyStrokesProperties --|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchParametersProperties --|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementUIElementActionSomewayProperties --|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.SeleniumBrowserWebElementActionAfterSearchWebElementFromWebElementCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.ReplaceDataTableValueCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.ReplaceDataTableRowValueCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.FilterDataTableColumnByRowValueCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.ReplaceDataTableColumnValueCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.FilterDataTableRowByColumnValueCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.AddDataTableRowCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.FilterDictionaryCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.ReplaceDictionaryCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.ReplaceListCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.FilterListCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.ExtractionTextCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.CreateListCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.SeleniumBrowserGetWebElementsValuesAsDataTableCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.AddDictionaryItemCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.BeginLoopCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.BeginMultiLoopCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.BeginMultiIfCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.BeginIfCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.DatabaseExecuteQueryCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.HTTPExecuteRESTAPICommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.SeleniumBrowserWebElementActionAfterSearchWebElementCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.ShowUserInputDialogCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.ExecuteDLLCommand ..|> taskt.Core.Automation.Commands.IHaveDataTableElements
taskt.Core.Automation.Commands.SendAdvancedKeyStrokesFromWindowHandleCommand ..|> taskt.Core.Automation.Commands.KeyMouseGroup.ISendAdvancedKeyStrokesProperties
taskt.Core.Automation.Commands.SendAdvancedKeyStrokesCommand ..|> taskt.Core.Automation.Commands.KeyMouseGroup.ISendAdvancedKeyStrokesProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchParametersProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchParametersProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchParametersProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementChildrenSearchParametersProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionSomewayCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementUIElementActionSomewayProperties
taskt.Core.Automation.Commands.SeleniumBrowserGetOneWebElementValuesAsDataTableCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetOneWebElementValuesAsListCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetOneWebElementValuesAsDictionaryCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchParametersProperties
taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchAnyUIElementProperties --|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchParametersProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionSomewayCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByXPathCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionSomewayCommands
taskt.Core.Automation.Commands.UIAutomationSearchChildrenUIElementsInformationCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchChildUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AChildrenSearchUIElementsFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.ADescendantsSearchUIElementsFromWindowNameByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsInformationFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowNameCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchAnyUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands ..|> taskt.Core.Automation.Commands.UIAutomationGroup.IUIElementDescendantsSearchAnyUIElementProperties
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByXPathCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsInformationFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchUIElementsFromWindowHandleByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowNameByTreeWalkerCommands --|> taskt.Core.Automation.Commands.ADescendantsSearchUIElementsFromWindowNameByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementsInformationFromWindowNameCommand --|> taskt.Core.Automation.Commands.ADescendantsSearchUIElementsFromWindowNameByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementByXPathFromWindowNameCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByXPathCommands
taskt.Core.Automation.Commands.UIAutomationWaitForUIElementToExistsCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationCheckUIElementExistsCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromUIElementCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromUIElementByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowHandleByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationSearchUIElementFromWindowNameCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.ADescendantsSearchAnyUIElementFromWindowNameByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowHandleCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
taskt.Core.Automation.Commands.UIAutomationUIElementActionAfterSearchUIElementFromWindowNameCommand --|> taskt.Core.Automation.Commands.UIAutomationGroup.AUIElementActionFromWindowSomethingByTreeWalkerCommands
@enduml