@startuml
GetSquareRootCommand --> AMathValueResultCommands
AMathValueResultCommands --> ScriptCommand
AMathValueResultCommands --> IMathValueResultProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml