@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
abstract class "AInverseTrignometricCommands"{
+v_AngleType : String <<get>> <<set>> 
+v_WhenValueIsOutOfRange : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IInverseTrignometricProperties" {
+{abstract} v_WhenValueIsOutOfRange : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
class "GetArccosCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "GetArcsinCommand" <<sealed>> {
+RunCommand() : void 
}
}

taskt.Core.Automation.Commands.AInverseTrignometricCommands ..|> taskt.Core.Automation.Commands.IInverseTrignometricProperties
taskt.Core.Automation.Commands.GetArccosCommand --|> taskt.Core.Automation.Commands.AInverseTrignometricCommands
taskt.Core.Automation.Commands.GetArcsinCommand --|> taskt.Core.Automation.Commands.AInverseTrignometricCommands
@enduml