@startuml
left to right direction
package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserWebElementActionAfterSearchWebElementFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+GetDisplayValue() : String
+v_WebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumBrowserWebElementActionAfterSearchWebElementCommands"{
#SearchAndActionProcess() : void 
+AfterShown() : void 
#cmbSearchType_SelectionChangeCommited() : void 
#cmbSeleniumAction_SelectionChangeCommitted() : void 
-{static} AddDataTableRows() : void 
-{static} AddDataTableRows() : void 
-{static} ActionParameterProcess() : void 
-{static} CreateComboBox() : DataGridViewComboBoxCell
+BeforeValidate() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_WebElementAction : String <<get>> <<set>> 
+v_WebActionParameterTable : DataTable <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
+v_WhenFailAction : String <<get>> <<set>> 
+v_ScrollToWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserWebElementActionAfterSearchWebElementCommand" <<sealed>> {
+RunCommand() : void 
+GetDisplayValue() : String
+v_InstanceName : String <<get>> <<set>> 
}
}

taskt.Core.Automation.Commands.SeleniumBrowserWebElementActionAfterSearchWebElementFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumBrowserWebElementActionAfterSearchWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserWebElementActionAfterSearchWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumBrowserWebElementActionAfterSearchWebElementCommands
@enduml