@startuml
ASeleniumGetOneResultFromWebElementCommands --> ASeleniumGetFromWebElementCommands
ASeleniumGetOneResultFromWebElementCommands --> IResultProperties
ASeleniumGetFromWebElementCommands --> ASeleniumWebElementActionAndScrollCommands
ASeleniumGetFromWebElementCommands --> ISeleniumGetFromWebElementProperties
ASeleniumWebElementActionAndScrollCommands --> ASeleniumWebElementActionCommands
ASeleniumWebElementActionAndScrollCommands --> ISeleniumWebElementActionAndScrollProperties
ASeleniumWebElementActionCommands --> ASeleniumDoSomethingToWebElementCommands
ASeleniumWebElementActionCommands --> ISeleniumWebElementActionProperties
ASeleniumDoSomethingToWebElementCommands --> ScriptCommand
ASeleniumDoSomethingToWebElementCommands --> ISeleniumDoSomethingToWebElementProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml