@startuml
ASeleniumGetFromWebDriverCommands --> ASeleniumDoSomethingToWebDriverCommands
ASeleniumGetFromWebDriverCommands --> IResultProperties
ASeleniumDoSomethingToWebDriverCommands --> ScriptCommand
ASeleniumDoSomethingToWebDriverCommands --> ISeleniumDoSomethingToWebDriverProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml