@startuml
package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumSearchWebElementFromWebElementCommands"{
#SearchWebElementAction() : void 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumSearchMultiWebElementsFromWebElementCommands"{
#SearchMultiWebElementsAction() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetMatchedWebElementsHTMLAsListFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetWebElementsCountFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserCheckWebElementExistsFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchMultiWebElementsFromWebElementCommands <|-- taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebElementCommands
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchMultiWebElementsFromWebElementCommands <|-- taskt.Core.Automation.Commands.SeleniumBrowserGetMatchedWebElementsHTMLAsListFromWebElementCommand
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchMultiWebElementsFromWebElementCommands <|-- taskt.Core.Automation.Commands.SeleniumBrowserGetWebElementsCountFromWebElementCommand
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebElementCommands <|-- taskt.Core.Automation.Commands.SeleniumBrowserCheckWebElementExistsFromWebElementCommand
@enduml