@startuml
package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetOneWebElementValuesAsDataTableCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumGetOneWebElementValuesAsSomethingCommands"{
+BeforeValidate() : void 
#GetOneWebElementMultiValuesAction() : void 
+v_AttributesName : DataTable <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetOneWebElementValuesAsListCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetOneWebElementValuesAsDictionaryCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}


taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands <|-- taskt.Core.Automation.Commands.SeleniumBrowserGetOneWebElementValuesAsDataTableCommand
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands <|-- taskt.Core.Automation.Commands.SeleniumBrowserGetOneWebElementValuesAsListCommand
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands <|-- taskt.Core.Automation.Commands.SeleniumBrowserGetOneWebElementValuesAsDictionaryCommand
@enduml