@startuml
left to right direction
package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ISeleniumDoSomethingToWebElementProperties" {
+{abstract} v_WebElement : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ICanHandleWebElement" {
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumDoSomethingToWebElementCommands"{
+v_WebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ISeleniumWebElementActionProperties" {
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserWaitForWebElementToExistsFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_WebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumWebElementActionCommands"{
+v_WhenFailAction : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserSearchShadowDOMWebElementFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserSearchWebElementFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ISeleniumWebElementActionAndScrollProperties" {
+{abstract} v_ScrollToWebElement : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserWebElementActionAfterSearchWebElementFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+GetDisplayValue() : String
+v_WebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumWebElementActionAndScrollCommands"{
+v_ScrollToWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserScrollToWebElementCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ISeleniumGetFromWebElementProperties" {
+{abstract} v_WhenValueCanNotRetrieved : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumGetFromWebElementCommands"{
+v_WhenValueCanNotRetrieved : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserRemoveWebElementCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserClickWebElementCommand" <<sealed>> {
+RunCommand() : void 
-cmdClickType_SelectinChange() : void 
+v_ClickType : String <<get>> <<set>> 
+v_XOffset : String <<get>> <<set>> 
+v_YOffset : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserSendSpecialKeystrokesToWebElementCommand" <<sealed>> {
+RunCommand() : void 
-CreateSendKeyList() : List
+v_SendKey : String <<get>> <<set>> 
+v_ControlKey : String <<get>> <<set>> 
+v_ShiftKey : String <<get>> <<set>> 
+v_AltKey : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserSwitchToFrameWebElementCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserSelectOptionForWebElementCommand" <<sealed>> {
+RunCommand() : void 
-cmbSelectionType_SelectionChange() : void 
+v_SelectionType : String <<get>> <<set>> 
+v_SelectionValue : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserSetTextToWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_TextToSet : String <<get>> <<set>> 
+v_ClearTextBeforeSetting : String <<get>> <<set>> 
+v_EncryptedText : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserClearTextInWebElementCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumGetOneResultFromWebElementCommands"{
#StoreEmptyValueToResult() : void 
+{abstract} v_Result : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumSearchMultiWebElementsFromWebElementCommands"{
#SearchMultiWebElementsAction() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetWebElementSizeCommand" <<sealed>> {
+RunCommand() : void 
+v_Width : String <<get>> <<set>> 
+v_Height : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetWebElementPositionCommand" <<sealed>> {
+RunCommand() : void 
+v_XPosition : String <<get>> <<set>> 
+v_YPosition : String <<get>> <<set>> 
+v_PositionBase : String <<get>> <<set>> 
+v_PositionType : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
abstract class "ASeleniumGetWebElementSelectorFromWebElementCommands"{
+v_Result : String <<get>> <<set>> 
+v_BeliveIDAttribute : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetSpecialValueFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_ValueType : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetHTMLFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetOptionsFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_AttributeName : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetTextFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetAttributeFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_AttributeName : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumSearchWebElementFromWebElementCommands"{
#SearchWebElementAction() : void 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetMatchedWebElementsHTMLAsListFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetWebElementsCountFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetCSSSelectorFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetXPathFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserCheckWebElementExistsFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumDoSomethingToWebElementProperties --|> taskt.Core.Automation.Commands.WebBrowserGroup.ICanHandleWebElement
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumDoSomethingToWebElementCommands ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumDoSomethingToWebElementProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumWebElementActionProperties --|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumDoSomethingToWebElementProperties
taskt.Core.Automation.Commands.SeleniumBrowserWaitForWebElementToExistsFromWebElementCommand ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumDoSomethingToWebElementProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionCommands --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumDoSomethingToWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserSearchShadowDOMWebElementFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumDoSomethingToWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserSearchWebElementFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumDoSomethingToWebElementCommands
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionCommands ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumWebElementActionProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumWebElementActionAndScrollProperties --|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumWebElementActionProperties
taskt.Core.Automation.Commands.SeleniumBrowserWebElementActionAfterSearchWebElementFromWebElementCommand ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumWebElementActionProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionAndScrollCommands --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionCommands
taskt.Core.Automation.Commands.SeleniumBrowserScrollToWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionCommands
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionAndScrollCommands ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumWebElementActionAndScrollProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumGetFromWebElementProperties --|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumWebElementActionAndScrollProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetFromWebElementCommands --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionAndScrollCommands
taskt.Core.Automation.Commands.SeleniumBrowserRemoveWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionAndScrollCommands
taskt.Core.Automation.Commands.SeleniumBrowserClickWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionAndScrollCommands
taskt.Core.Automation.Commands.SeleniumBrowserSendSpecialKeystrokesToWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionAndScrollCommands
taskt.Core.Automation.Commands.SeleniumBrowserSwitchToFrameWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionAndScrollCommands
taskt.Core.Automation.Commands.SeleniumBrowserSelectOptionForWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionAndScrollCommands
taskt.Core.Automation.Commands.SeleniumBrowserSetTextToWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionAndScrollCommands
taskt.Core.Automation.Commands.SeleniumBrowserClearTextInWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumWebElementActionAndScrollCommands
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetFromWebElementCommands ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumGetFromWebElementProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneResultFromWebElementCommands --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetFromWebElementCommands
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchMultiWebElementsFromWebElementCommands --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetWebElementSizeCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetWebElementPositionCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetFromWebElementCommands
taskt.Core.Automation.Commands.ASeleniumGetWebElementSelectorFromWebElementCommands --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneResultFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetSpecialValueFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneResultFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetHTMLFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneResultFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetOptionsFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneResultFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetTextFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneResultFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetAttributeFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneResultFromWebElementCommands
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebElementCommands --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchMultiWebElementsFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetMatchedWebElementsHTMLAsListFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchMultiWebElementsFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetWebElementsCountFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchMultiWebElementsFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetCSSSelectorFromWebElementCommand --|> taskt.Core.Automation.Commands.ASeleniumGetWebElementSelectorFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetXPathFromWebElementCommand --|> taskt.Core.Automation.Commands.ASeleniumGetWebElementSelectorFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserCheckWebElementExistsFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebElementCommands
@enduml