@startuml
package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ICanHandleWebElement" {
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ICanHandleWebDriver" {
}
}


taskt.Core.Automation.Commands.WebBrowserGroup.ICanHandleWebDriver <|-- taskt.Core.Automation.Commands.WebBrowserGroup.ICanHandleWebElement
@enduml