@startuml
left to right direction
package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumSearchWebElementFromWebDriverCommands"{
#SearchWebElementAction() : void 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ISeleniumSearchWebElementParametersProperties" {
+{abstract} v_WebElementIndex : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumSearchWebElementFromWebElementCommands"{
#SearchWebElementAction() : void 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserSearchShadowDOMWebElementFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserWaitForWebElementToExistsFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserWebElementActionAfterSearchWebElementFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+AfterShown() : void 
-cmbSearchType_SelectionChangeCommited() : void 
-cmbSeleniumAction_SelectionChangeCommitted() : void 
-{static} AddDataTableRows() : void 
-{static} AddDataTableRows() : void 
-{static} ActionParameterProcess() : void 
-{static} CreateComboBox() : DataGridViewComboBoxCell
+GetDisplayValue() : String
+BeforeValidate() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_WebElementAction : String <<get>> <<set>> 
+v_WebActionParameterTable : DataTable <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
+v_ScrollToWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserSearchWebElementFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserWaitForWebElementToExistsCommand" <<sealed>> {
+RunCommand() : void 
+v_InstanceName : String <<get>> <<set>> 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserSearchWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserWebElementActionAfterSearchWebElementCommand" <<sealed>> {
+RunCommand() : void 
+AfterShown() : void 
-cmbSearchType_SelectionChangeCommited() : void 
-cmbSeleniumAction_SelectionChangeCommitted() : void 
-{static} AddDataTableRows() : void 
-{static} AddDataTableRows() : void 
-{static} ActionParameterProcess() : void 
-{static} CreateComboBox() : DataGridViewComboBoxCell
+GetDisplayValue() : String
+BeforeValidate() : void 
+v_SearchMethod : String <<get>> <<set>> 
+v_SearchParameter : String <<get>> <<set>> 
+v_SelectionMethod : String <<get>> <<set>> 
+v_WebElementIndex : String <<get>> <<set>> 
+v_WebElementAction : String <<get>> <<set>> 
+v_WebActionParameterTable : DataTable <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
+v_ScrollToWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
abstract class "ASeleniumGetOneWebElementValuesAsSomethingCommands"{
+BeforeValidate() : void 
#GetOneWebElementMultiValuesAction() : void 
+v_AttributesName : DataTable <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserCheckWebElementExistsCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetTableValuesAsDataTableCommand" <<sealed>> {
+RunCommand() : void 
+v_AttributeName : String <<get>> <<set>> 
+v_Result : String <<get>> <<set>> 
+v_FirstRowMethod : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserCheckWebElementExistsFromWebElementCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
+v_WaitTimeForWebElement : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetOneWebElementValuesAsDataTableCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetOneWebElementValuesAsListCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

package "taskt.Core.Automation.Commands"{
class "SeleniumBrowserGetOneWebElementValuesAsDictionaryCommand" <<sealed>> {
+RunCommand() : void 
+v_Result : String <<get>> <<set>> 
}
}

taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebDriverCommands ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumSearchWebElementParametersProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebElementCommands ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumSearchWebElementParametersProperties
taskt.Core.Automation.Commands.SeleniumBrowserSearchShadowDOMWebElementFromWebElementCommand ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumSearchWebElementParametersProperties
taskt.Core.Automation.Commands.SeleniumBrowserWaitForWebElementToExistsFromWebElementCommand ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumSearchWebElementParametersProperties
taskt.Core.Automation.Commands.SeleniumBrowserWebElementActionAfterSearchWebElementFromWebElementCommand ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumSearchWebElementParametersProperties
taskt.Core.Automation.Commands.SeleniumBrowserSearchWebElementFromWebElementCommand ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumSearchWebElementParametersProperties
taskt.Core.Automation.Commands.SeleniumBrowserWaitForWebElementToExistsCommand ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumSearchWebElementParametersProperties
taskt.Core.Automation.Commands.SeleniumBrowserSearchWebElementCommand ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumSearchWebElementParametersProperties
taskt.Core.Automation.Commands.SeleniumBrowserWebElementActionAfterSearchWebElementCommand ..|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumSearchWebElementParametersProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebDriverCommands
taskt.Core.Automation.Commands.SeleniumBrowserCheckWebElementExistsCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebDriverCommands
taskt.Core.Automation.Commands.SeleniumBrowserSearchWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebDriverCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetTableValuesAsDataTableCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebDriverCommands
taskt.Core.Automation.Commands.SeleniumBrowserCheckWebElementExistsFromWebElementCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumSearchWebElementFromWebElementCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetOneWebElementValuesAsDataTableCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetOneWebElementValuesAsListCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands
taskt.Core.Automation.Commands.SeleniumBrowserGetOneWebElementValuesAsDictionaryCommand --|> taskt.Core.Automation.Commands.WebBrowserGroup.ASeleniumGetOneWebElementValuesAsSomethingCommands
@enduml