@startuml
left to right direction
package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ISeleniumWebElementActionProperties" {
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ISeleniumDoSomethingToWebElementProperties" {
+{abstract} v_WebElement : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands"{
Interface "IWhenFailActionBehaviorProperties" {
+{abstract} v_WhenFailAction : String <<get>> <<set>> <<abstract>> 
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ICanHandleWebElement" {
}
}

package "taskt.Core.Automation.Commands"{
Interface "IExpandableProperties" {
}
}

package "taskt.Core.Automation.Commands.WebBrowserGroup"{
Interface "ICanHandleWebDriver" {
}
}

taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumWebElementActionProperties --|> taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumDoSomethingToWebElementProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumWebElementActionProperties --|> taskt.Core.Automation.Commands.IWhenFailActionBehaviorProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumDoSomethingToWebElementProperties --|> taskt.Core.Automation.Commands.WebBrowserGroup.ICanHandleWebElement
taskt.Core.Automation.Commands.WebBrowserGroup.ISeleniumDoSomethingToWebElementProperties --|> taskt.Core.Automation.Commands.IExpandableProperties
taskt.Core.Automation.Commands.WebBrowserGroup.ICanHandleWebElement --|> taskt.Core.Automation.Commands.WebBrowserGroup.ICanHandleWebDriver
@enduml