@startuml
SeleniumBrowserExecuteJavaScriptFromCodeCommand --> ASeleniumExecuteJavaScriptCommands
SeleniumBrowserExecuteJavaScriptFromCodeCommand --> ICanExecuteJavaScriptToWebDriver
ASeleniumExecuteJavaScriptCommands --> ASeleniumWebDriverActionCommands
ASeleniumExecuteJavaScriptCommands --> ISeleniumExecuteJavaScriptProperties
ASeleniumWebDriverActionCommands --> ASeleniumDoSomethingToWebDriverCommands
ASeleniumWebDriverActionCommands --> ISeleniumWebDriverActionProperties
ASeleniumDoSomethingToWebDriverCommands --> ScriptCommand
ASeleniumDoSomethingToWebDriverCommands --> ISeleniumDoSomethingToWebDriverProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml