@startuml
SeleniumBrowserGetWebBrowserSizeCommand --> ASeleniumWebDriverActionCommands
SeleniumBrowserGetWebBrowserSizeCommand --> ISizeProperties
SeleniumBrowserGetWebBrowserSizeCommand --> ICanExecuteJavaScriptToWebDriver
ASeleniumWebDriverActionCommands --> ASeleniumDoSomethingToWebDriverCommands
ASeleniumWebDriverActionCommands --> ISeleniumWebDriverActionProperties
ASeleniumDoSomethingToWebDriverCommands --> ScriptCommand
ASeleniumDoSomethingToWebDriverCommands --> ISeleniumDoSomethingToWebDriverProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml