@startuml
SeleniumBrowserAttachCreateWebBrowserInstanceCommand --> ASeleniumCreateWebDriverCommands
ASeleniumCreateWebDriverCommands --> ASeleniumDoSomethingToWebDriverCommands
ASeleniumCreateWebDriverCommands --> ISeleniumCreateWebDriverProperties
ASeleniumDoSomethingToWebDriverCommands --> ScriptCommand
ASeleniumDoSomethingToWebDriverCommands --> ISeleniumDoSomethingToWebDriverProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml