@startuml
SeleniumBrowserSearchShadowDOMWebElementFromWebElementCommand --> ASeleniumDoSomethingToWebElementCommands
SeleniumBrowserSearchShadowDOMWebElementFromWebElementCommand --> ISeleniumSearchWebElementParametersProperties
ASeleniumDoSomethingToWebElementCommands --> ScriptCommand
ASeleniumDoSomethingToWebElementCommands --> ISeleniumDoSomethingToWebElementProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml