@startuml
SeleniumBrowserCreateWebBrowserInstanceCommand --> ASeleniumCreateWebDriverCommands
SeleniumBrowserCreateWebBrowserInstanceCommand --> ICanHandleWindowHandle
ASeleniumCreateWebDriverCommands --> ASeleniumDoSomethingToWebDriverCommands
ASeleniumCreateWebDriverCommands --> ISeleniumCreateWebDriverProperties
ASeleniumDoSomethingToWebDriverCommands --> ScriptCommand
ASeleniumDoSomethingToWebDriverCommands --> ISeleniumDoSomethingToWebDriverProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml