@startuml
SeleniumBrowserNavigateForwardCommand --> ASeleniumWebDriverActionCommands
ASeleniumWebDriverActionCommands --> ASeleniumDoSomethingToWebDriverCommands
ASeleniumWebDriverActionCommands --> ISeleniumWebDriverActionProperties
ASeleniumDoSomethingToWebDriverCommands --> ScriptCommand
ASeleniumDoSomethingToWebDriverCommands --> ISeleniumDoSomethingToWebDriverProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml