@startuml
SeleniumBrowserSearchWebElementFromWebElementCommand --> ASeleniumDoSomethingToWebElementCommands
SeleniumBrowserSearchWebElementFromWebElementCommand --> ISeleniumSearchWebElementParametersProperties
ASeleniumDoSomethingToWebElementCommands --> ScriptCommand
ASeleniumDoSomethingToWebElementCommands --> ISeleniumDoSomethingToWebElementProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml