@startuml
SeleniumBrowserGetOneWebElementValuesAsListCommand --> ASeleniumGetOneWebElementValuesAsSomethingCommands
SeleniumBrowserGetOneWebElementValuesAsListCommand --> IListResultProperties
ASeleniumGetOneWebElementValuesAsSomethingCommands --> ASeleniumSearchWebElementFromWebDriverCommands
ASeleniumGetOneWebElementValuesAsSomethingCommands --> IHaveDataTableElements
ASeleniumSearchWebElementFromWebDriverCommands --> ASeleniumSearchMultiWebElementsFromWebDriverCommands
ASeleniumSearchWebElementFromWebDriverCommands --> ISeleniumSearchWebElementParametersProperties
ASeleniumSearchMultiWebElementsFromWebDriverCommands --> ASeleniumGetFromWebDriverCommands
ASeleniumSearchMultiWebElementsFromWebDriverCommands --> ISeleniumSearchMultiWebElementsParametersProperties
ASeleniumGetFromWebDriverCommands --> ASeleniumDoSomethingToWebDriverCommands
ASeleniumGetFromWebDriverCommands --> IResultProperties
ASeleniumDoSomethingToWebDriverCommands --> ScriptCommand
ASeleniumDoSomethingToWebDriverCommands --> ISeleniumDoSomethingToWebDriverProperties
ScriptCommand --> IUIParameterProperties
ScriptCommand --> ICommandIDProperties
@enduml