@startuml
package "taskt.Core.Script"{
class "InnerScriptVariable" {
+Dispose() : void 
#Dispose() : void 
#Finalize() : void 
-engine : taskt.Core.Automation.Engine.AutomationEngineInstance
}
}

package "taskt.Core.Script"{
class "ScriptVariable" {
+GetDisplayValue() : String
-GetDisplayValue() : String
-GetDisplayValue() : String
-GetDisplayValue() : String
-GetDisplayValue() : String
-GetDisplayValue() : String
-GetDisplayValue() : String
-GetDisplayValue() : String
-GetDisplayValue() : String
-GetDisplayValue() : String
+VariableName : String <<get>> <<set>> 
+VariableValue : Object <<get>> <<set>> 
+CurrentPosition : int
}
}


taskt.Core.Script.ScriptVariable <|-- taskt.Core.Script.InnerScriptVariable
@enduml